"""review_scope.py — the diff a lens actually reads. (SCC-447 Part 2)

⛔ WHAT THIS FILE EXISTS FOR, measured. SCC-441 handed its review engine a 155-file, 1.46 MB
diff. Forty-eight of those files were byte-copy MIRRORS of files already in the diff, and
twenty-six were the lane's OWN records — the walkthrough describing the work, the plan, the SOP
page. A lens reading a mirror finds the same defect twice and reports it twice; a lens reading
the walkthrough reviews the description of the code instead of the code. Neither is a review.

The script answers one question — *what should a lens read?* — and its two halves are separate
on purpose: WHICH COMMITS (a part, not a lane) and WHICH FILES (masters, not copies of them).

⛔ THERE IS NO BYTE CAP, and that is a deliberate refusal. A cap truncates the diff at an
arbitrary line and the lens never learns what it did not see, which is the failure mode a
review cannot detect from the inside. The size of a review is the size of a part; if a part is
too big to review, the fix is a smaller part.

Every case builds a REAL git repository in a temp dir and runs the real script against it.
Stdlib only, no pytest — same constraint as every sibling here.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

from _harness import Cases

ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / ".agents" / "scripts" / "review_scope.py"

# The withheld classes, one fixture file each, so a class that stops working names itself.
MASTERS = (".agents/rules/house.md", ".agents/scripts/tool.py", ".agents/commands/door.md",
           ".agents/notes.md", ".agents/rules/bytes.md")   # bytes.md carries a byte the default codec rejects
MIRRORS = (".claude/rules/house.md", ".opencode/commands/door.md",
           ".roo/rules/house.md", ".agent/notes.md")
# ⛔ A MIRROR is a BYTE COPY of its master, not a prefix (SCC-447 tip review, receipt x5): the fixture
# writes each as its master's bytes. An AUTHORED file under a mirror prefix with no master at all is
# not a mirror - `.claude/settings.json` holds the branch-delete guard hook and the deny rows, and
# the prefix rule had withheld it from every review.
MIRROR_MASTER = {".claude/rules/house.md": ".agents/rules/house.md",
                 ".opencode/commands/door.md": ".agents/commands/door.md",
                 ".roo/rules/house.md": ".agents/rules/house.md",
                 ".agent/notes.md": ".agents/notes.md"}
AUTHORED = (".claude/settings.json",)
GENERATED = ("generated/launcher.md", "generated/seat.md")   # marker in the TEXT, not the path
RECORDS = ("_artifacts/lane/walkthrough.md", "_bmad-output/board.md",
           "docs/_scc_sops_prds/manual.md")

# The two shapes `sync-agents.ps1` actually writes: a launcher's H1, and an HTML comment (SCC-350
# seats). A generated file DECLARES itself on a heading or comment line — that is the whole signal.
GEN_TEXT = {
    "generated/launcher.md": "# /launcher - launcher (GENERATED by sync-agents; do not edit)\n",
    "generated/seat.md": "<!-- GENERATED by sync-agents (SCC-350; do not edit). -->\n",
}

# ⛔ A MASTER that merely MENTIONS the marker — in a docstring, a table row, a string constant —
# is not generated. The bare-substring rule withheld `review_scope.py` ITSELF (its docstring names
# the class), `test_review_scope.py`, `test_command_surfaces.py`, the scripts INDEX and two command
# masters from every review, and nobody saw it until this lane's own review cut printed the list
# (SCC-447, found at the tip). Every one of them must be KEPT.
MENTIONS = (".agents/scripts/mentions.py", ".agents/commands/mentions.md")
MENTION_TEXT = {
    ".agents/scripts/mentions.py": (
        '"""A master that talks about launchers.\n\n'
        '    generated   text carries `GENERATED by sync-agents`    - output, not authorship\n'
        '"""\nMARKER = "GENERATED by sync-agents"\n'
    ),
    ".agents/commands/mentions.md": (
        "# /mentions\n\n| Rule | Detail |\n|---|---|\n"
        "| **Generated files are not edited** | a `GENERATED by sync-agents` skill. Edit the command |\n"
    ),
}


def _git(repo: Path, *args: str) -> str:
    env = dict(os.environ, GIT_AUTHOR_NAME="t", GIT_AUTHOR_EMAIL="t@t",
               GIT_COMMITTER_NAME="t", GIT_COMMITTER_EMAIL="t@t")
    out = subprocess.run(("git", *args), cwd=repo, env=env, capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout.strip()


def _write(repo: Path, rel: str, text: str) -> None:
    p = repo / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")


def _run(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run((sys.executable, str(SCRIPT), "--repo", str(repo), *args),
                          capture_output=True, text=True)


def _build(tmp: Path) -> dict:
    """A lane with two parts: the lane key's own commit, and a rider's.

    Mirrors the house convention `SCC-<parent> rider SCC-<child>: …` (work-consolidation
    rule 2), because that is the only thing in a subject that tells the two apart.
    """
    repo = tmp / "lane"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")

    _write(repo, "README.md", "seed\n")
    _git(repo, "add", "README.md")
    _git(repo, "commit", "-qm", "SCC-000 seed: the base")
    base = _git(repo, "rev-parse", "HEAD")

    _git(repo, "checkout", "-qb", "chore/SCC-447-review-disposition")

    # Part one, the lane key's own: one file of every class.
    for rel in MASTERS + RECORDS:
        _write(repo, rel, f"part one: {rel}\n")
    (repo / ".agents/rules/bytes.md").write_bytes(b"# rule\n\xff not utf-8\n")   # receipt b7
    for rel in MIRRORS:
        _write(repo, rel, f"part one: {MIRROR_MASTER[rel]}\n")   # the master's bytes, exactly
    for rel in AUTHORED:
        _write(repo, rel, '{"hooks": {"PreToolUse": []}}\n')
    for rel in GENERATED:
        _write(repo, rel, f"{GEN_TEXT[rel]}part one: {rel}\n")
    for rel in MENTIONS:
        _write(repo, rel, MENTION_TEXT[rel])
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "SCC-447 doctrine: the rule and its copies")
    # A subject carrying a key-shaped token that is no ticket (receipt x4): measured in real history
    # - UTF-8 x3, H-1 x4, CS-18, CR-3, AC-6 - and the old rule made each one a phantom PART.
    _write(repo, ".agents/scripts/utf.py", "utf\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "SCC-447 fix(scripts): force UTF-8 stdout so the PC stops needing PYTHONIOENCODING")
    part_one = _git(repo, "rev-parse", "HEAD")

    # Part two, a rider: a master of its own, so selecting one part cannot return the other's.
    _write(repo, ".agents/scripts/rider.py", "part two\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "SCC-447 rider SCC-448: the rider part")
    part_two = _git(repo, "rev-parse", "HEAD")

    return {"repo": repo, "base": base, "one": part_one, "two": part_two}


def main() -> int:
    c = Cases("review_scope")

    with tempfile.TemporaryDirectory() as td:
        fx = _build(Path(td))
        repo, base = fx["repo"], fx["base"]
        one, two = fx["one"], fx["two"]

        # ── 1. the withheld classes, and the masters that survive them ──────────────────
        if c.block("1 · mirrors, generated launchers and records are withheld"):
            r = _run(repo, "--base", base, "--range", f"{base}..{one}")
            out = r.stdout
            c.check("the run succeeds", r.returncode == 0, r.stderr[-400:])
            for rel in MASTERS:
                c.check(f"master kept: {rel}", rel in out and "withheld" not in
                        _line_for(out, rel), f"{rel} did not survive")
            for rel in MIRRORS:
                c.check(f"mirror withheld: {rel}", _withheld_as(out, rel) == "mirror",
                        f"{rel} class={_withheld_as(out, rel)!r}")
            for rel in GENERATED:
                c.check(f"generated withheld: {rel}", _withheld_as(out, rel) == "generated",
                        f"{rel} class={_withheld_as(out, rel)!r} — the MARKER is in the text, "
                        "so a path-only rule cannot see it")
            for rel in RECORDS:
                c.check(f"record withheld: {rel}", _withheld_as(out, rel) == "record",
                        f"{rel} class={_withheld_as(out, rel)!r}")
            # ⛔ The marker is a DECLARATION on a heading/comment line, never a substring. A master
            # that mentions it in prose is kept — the bare rule withheld this script from its own
            # review, and the review that found it was the first one ever to read the list.
            for rel in MENTIONS:
                c.check(f"a master that MENTIONS the marker is kept: {rel}",
                        rel in out and "withheld" not in _line_for(out, rel),
                        f"{rel} class={_withheld_as(out, rel)!r} — a substring rule withholds "
                        "every master that talks about launchers, including review_scope.py itself")
            for rel in AUTHORED:
                c.check(f"an AUTHORED file under a mirror prefix, with no master, is kept: {rel}",
                        rel in out and "withheld" not in _line_for(out, rel),
                        f"{rel} class={_withheld_as(out, rel)!r} - a prefix is not a mirror; a byte "
                        "copy of a master is, and this one has no master")
            # ⛔ The COUNT and the BYTES are the only evidence the caller gets that the diff
            # it is about to hand a lens is the one this script chose. Prose is not enough.
            c.check("kept count and bytes are both reported",
                    "kept:" in out and "bytes" in out,
                    "the summary names neither the count nor the size")

        # ── 2. commits group by part key, and a rider key beats the lane key ────────────
        if c.block("2 · commits group by part key, rider over lane"):
            r = _run(repo, "--base", base)
            out = r.stdout + r.stderr
            c.check("both part keys are named", "SCC-447" in out and "SCC-448" in out,
                    "a two-part range reported fewer than two keys")
            # The rider commit carries BOTH keys in its subject. Reading left-to-right would
            # file it under the lane, which is the whole bug this convention exists to avoid.
            c.check("the rider commit files under the RIDER, not the lane",
                    _key_of(out, "SCC-448") == 1,
                    "the rider's commit was counted under the lane key")
            c.check("a key-shaped token that is no ticket (UTF-8) is not a part - the rider word is",
                    "part UTF-8" not in out and _key_of(out, "SCC-447") == 2,
                    f"parts printed: {[l for l in out.splitlines() if l.strip().startswith('part')]}")

        # ── 3. ambiguity is a refusal, never a guess ────────────────────────────────────
        if c.block("3 · two parts and no selector is exit 2, naming both"):
            r = _run(repo, "--base", base)
            c.check("exit 2", r.returncode == 2, f"exit={r.returncode}")
            both = r.stdout + r.stderr
            c.check("both keys are named in the refusal",
                    "SCC-447" in both and "SCC-448" in both, "the refusal does not say which")
            c.check("no patch is written on a refusal", "diff --git" not in r.stdout,
                    "a refusal still emitted a diff")

        # ── 4. --key selects one part's files and no other's ────────────────────────────
        if c.block("4 · --key selects one part only"):
            r = _run(repo, "--base", base, "--key", "SCC-448")
            c.check("the run succeeds", r.returncode == 0, r.stderr[-400:])
            c.check("the rider's own file is in scope", "rider.py" in r.stdout,
                    "the selected part's file is missing")
            c.check("the other part's master is NOT in scope", "tool.py" not in r.stdout,
                    "selecting one part returned another part's files")

        # ── 5. --range selects explicit commits ────────────────────────────────────────
        if c.block("5 · --range selects explicit commits"):
            r = _run(repo, "--base", base, "--range", f"{one}..{two}")
            c.check("the run succeeds", r.returncode == 0, r.stderr[-400:])
            c.check("only the ranged commit's file is in scope",
                    "rider.py" in r.stdout and "tool.py" not in r.stdout,
                    "the range did not bound the file set")

        # ── 6. --out writes the patch, and the counts are printed ──────────────────────
        if c.block("6 · --out writes the patch and reports both counts"):
            dest = Path(td) / "review" / "diff.patch"
            r = _run(repo, "--base", base, "--range", f"{base}..{one}", "--out", str(dest))
            c.check("the run succeeds", r.returncode == 0, r.stderr[-400:])
            c.check("the patch file exists", dest.is_file(), f"{dest} was not written")
            body = dest.read_text(encoding="utf-8") if dest.is_file() else ""
            c.check("the patch is a real diff", "diff --git" in body, "no diff in the file")
            c.check("the patch carries a master", "house.md" in body, "the master is absent")
            # ⛔ ANTI-VACUITY, and the one that matters most here: an EMPTY patch is a clean
            # review of nothing. A mirror in the patch would be the duplicate-finding bug.
            c.check("the patch carries NO mirror path",
                    ".opencode/" not in body and ".roo/" not in body,
                    "a mirror reached the lens after all")
            c.check("the summary reports kept and withheld counts",
                    "kept:" in r.stdout and "withheld:" in r.stdout,
                    "the caller cannot tell what was dropped")

        # ── 7. an empty selection is a refusal, never a clean patch ────────────────────
        if c.block("7 · an empty selection exits 2"):
            r = _run(repo, "--base", base, "--key", "SCC-999")
            c.check("exit 2", r.returncode == 2, f"exit={r.returncode}")
            c.check("the refusal says the selection is empty",
                    "empty" in (r.stdout + r.stderr).lower(), "the reason is not stated")
            c.check("no patch is written", "diff --git" not in r.stdout,
                    "an empty selection produced a diff anyway")

        # ── 8. --audit keeps every mirror, and still strips records ────────────────────
        # The D9 asymmetry, proved by the SAME fixture answering differently under one flag:
        # a self-audit must read the mirrors (drift between a master and its copy is the
        # defect it hunts), and must still never read the lane's own records.
        if c.block("8 · --audit keeps mirrors and still strips records"):
            plain = _run(repo, "--base", base, "--range", f"{base}..{one}")
            audit = _run(repo, "--base", base, "--range", f"{base}..{one}", "--audit")
            c.check("the audit run succeeds", audit.returncode == 0, audit.stderr[-400:])
            for rel in MIRRORS:
                c.check(f"--audit keeps {rel}", _withheld_as(audit.stdout, rel) is None,
                        f"{rel} was withheld from the audit")
                c.check(f"  ^ and the plain run withheld it", _withheld_as(plain.stdout, rel)
                        == "mirror", "the control did not withhold it, so the pair proves "
                        "nothing")
            for rel in RECORDS:
                c.check(f"--audit still withholds {rel}",
                        _withheld_as(audit.stdout, rel) == "record",
                        "a record reached the audit")

        # ── 9. a selection whose every file is withheld is a REFUSAL, never a patch of nothing ──
        # ⛔ Found by the SCC-447 tip review (Test-Adequacy lens, receipt t1): the guard existed and
        # nothing pinned it. Without it the kept list is empty, `git diff A..B --` gets an EMPTY
        # pathspec - which git reads as EVERYTHING - and the patch carries the record and the
        # launcher the script just announced it withheld.
        if c.block("9 · a selection whose every file is withheld exits 2 and writes no patch"):
            _write(repo, "_artifacts/lane/notes.md", "records only\n")
            _write(repo, "generated/launcher2.md",
                   "# /launcher2 - launcher (GENERATED by sync-agents; do not edit)\nnothing\n")
            _git(repo, "add", "-A")
            _git(repo, "commit", "-qm", "SCC-447 records: nothing a lens should read")
            three = _git(repo, "rev-parse", "HEAD")
            dest = Path(td) / "review" / "nothing.patch"
            r = _run(repo, "--base", base, "--range", f"{two}..{three}", "--out", str(dest))
            both = r.stdout + r.stderr
            c.check("9 exit 2 with every file withheld", r.returncode == 2, f"exit={r.returncode}")
            c.check("9 the refusal says every file was withheld",
                    "withheld" in both and "empty" in both.lower(), both[-300:])
            c.check("9 no patch is written", not dest.exists(), f"{dest} exists")

        # ── 10. a tree whose branch carries no key REFUSES instead of guessing (D6) ─────
        # ⛔ Found by the SCC-447 tip review (Acceptance lens, receipt a1): `lane_key()` reads the
        # branch name; detached, on `main`, or in an `isolation: "worktree"` agent tree it is `""`,
        # and `part_key_of` then filed every commit under the FIRST key in its subject - a
        # two-part lane read as one part and the exit-2 refusal never fired. "Never a guess" is
        # D6's whole sentence; a keyless tree was one more way to guess.
        if c.block("10 · a keyless tree refuses to group, and --range still works there"):
            _git(repo, "checkout", "-q", "--detach")
            try:
                r = _run(repo, "--base", base)
                both = r.stdout + r.stderr
                c.check("10 no selector on a keyless tree is exit 2", r.returncode == 2,
                        f"exit={r.returncode}: {both[-300:]}")
                c.check("10 the refusal names the missing key, not a phantom single part",
                        "no ticket key" in both and "more than one part" not in both, both[-300:])
                r = _run(repo, "--base", base, "--key", "SCC-448")
                both = r.stdout + r.stderr
                c.check("10 --key on a keyless tree is the same refusal",
                        r.returncode == 2 and "no ticket key" in both, f"exit={r.returncode}")
                r = _run(repo, "--base", base, "--range", f"{one}..{two}")
                c.check("10 --range needs no lane key and still selects the rider's file",
                        r.returncode == 0 and "rider.py" in r.stdout,
                        f"exit={r.returncode}: {(r.stdout + r.stderr)[-300:]}")
            finally:
                _git(repo, "checkout", "-q", "chore/SCC-447-review-disposition")

    return c.finish()


def _line_for(out: str, rel: str) -> str:
    for line in out.splitlines():
        if rel in line:
            return line
    return ""


def _withheld_as(out: str, rel: str) -> str | None:
    """The class named on the withheld line for `rel`, or None when it was kept."""
    line = _line_for(out, rel)
    if not line or "withheld" not in line:
        return None
    for cls in ("mirror", "generated", "record"):
        if cls in line:
            return cls
    return "unknown"


def _key_of(out: str, key: str) -> int:
    """How many commits the grouping report filed under `key`."""
    for line in out.splitlines():
        if key in line:
            for tok in line.replace("(", " ").replace(")", " ").split():
                if tok.isdigit():
                    return int(tok)
    return -1


if __name__ == "__main__":
    sys.exit(main())
