"""One door per platform per command (SCC-66) — the contract that keeps four menus honest.

Command docs, skill launchers, sync instructions and the actual on-disk caches used to be four
independent claims about the same thing, and they disagreed: 19 commands published BOTH a
`.claude/commands` mirror and a skill, Codex carried a deprecated `/prompts:` twin beside its
native skill, and the only way to notice was for a human to open a menu and find it wrong. That
is what burned the failed session this program came from.

The door model, and why it is forced rather than chosen:
  * Codex cannot expose repo-defined top-level `/name` commands at all — skills are its ONLY door;
  * Claude Code publishes a slash command for every `.claude/skills/*/SKILL.md` — so a skill is
    already a Claude door, and a command mirror beside it is a second one;
  * therefore ONE launcher skill serves Claude and Codex both, and `.claude/commands` +
    `~/.codex/prompts` are retired. opencode keeps its command mirror; Antigravity its workflow
    mirror (thin launcher when the body clears its 12k cap).

Reach comes from `platforms:` frontmatter (absent = universal), which splits the skill door two
ways: `.agents/skills` is Codex's NATIVE surface, so a claude-only command's launcher must live in
the `.claude/skills` cache only, and a codex-only command's launcher must be kept OUT of that cache.
Both directions are asserted — a door in the wrong place is exactly as wrong as a missing one.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

from _harness import Cases

ROOT = Path(__file__).resolve().parents[3]
ALL = ("claude", "opencode", "antigravity", "codex")
GEN = "GENERATED by sync-agents"

def wf_hand_owned(sync_ps1: str) -> set[str]:
    """workflows/ files the sync engine deliberately never writes — read FROM the engine.

    ⭐ Derived, not restated. This was `{"INDEX.md"}`: a hand-copied subset of the engine's
    three-entry `$excluded`, missing `smh-update-maps-indexes.md` and `smh-adviser-board.md`,
    which are hand-authored Antigravity workflows that legitimately differ from their command
    bodies (one is a condensed 2 KB variant of a 52 KB brain; the other is a 40 KB doc whose
    brain was later rewritten to 4 KB). The door-parity check below reported both as drift on
    its first run — a false positive caused entirely by the duplicated list.

    Two parsers of one fact must agree, so this reads the fact instead of copying it. A parse
    that returns nothing fails SAFE (nothing is exempted, so the sweep gets noisier, never
    quieter); the assertion in main() pins that it parsed at all.

    ⛔ ANCHORED to the function that owns it. An unscoped search takes the FIRST
    `$excluded = @(...)` in a 900-line file - and the file already has `$ExcludeDirs` /
    `$ExcludeFiles` in nearby scope, so a same-named local is not exotic. A clean-room pass
    defeated the unscoped version by adding an earlier array carrying one extra name: the
    ghost check then went silent on a genuinely orphaned workflow and the suite stayed green.
    OVERBROAD is the one direction that fails OPEN, which is why the scope is not optional.
    """
    start = sync_ps1.find("function Sync-AntigravityWorkflowMirror")
    m = re.search(r"\$excluded\s*=\s*@\(([^)]*)\)",
                  sync_ps1[start:] if start != -1 else sync_ps1)
    return set(re.findall(r"'([^']+)'", m.group(1))) if m else set()


def read(p: Path) -> str:
    # utf-8-SIG, not utf-8: 8 testarch-* commands carry a UTF-8 BOM. PowerShell's ReadAllLines
    # strips it, so sync-agents reads their `platforms: [opencode]` correctly - a plain utf-8 read
    # here leaves `﻿---` on line 1, which str.strip() does NOT remove (U+FEFF is not Python
    # whitespace), so the frontmatter probe misses and every one of them reads as UNIVERSAL. The
    # test then demands Claude/Codex/Antigravity doors for eight opencode-only bridges. Two parsers
    # of one file must agree byte-for-byte or the gate invents work.
    return p.read_text(encoding="utf-8-sig", errors="replace")


def fm_field(text: str, key: str) -> str | None:
    """A frontmatter scalar, or None. Used to compare a launcher against its brain."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for ln in lines[1:80]:
        if ln.strip() == "---":
            break
        if ln.startswith(f"{key}:"):
            return ln[len(key) + 1:].strip()
    return None


# The launcher's ONE instruction. Anchored to `read `…`` on purpose: a bare "does the path
# appear anywhere" test is satisfied by a stale `<!-- generated from … -->` comment sitting
# above a pointer that now names a DIFFERENT command - the repo's own
# comment-literals-invert-source-grep-tests lesson, reproduced against this very check.
LAUNCH_RE = re.compile(r"read\s+`\.agents/commands/([A-Za-z0-9._-]+\.md)`")


def is_launcher_for(body: str, brain: str, cmd_name: str) -> bool:
    """Is `body` the generated thin launcher for THIS command, still current?

    ⭐ Four conditions, and the third and fourth are what make the exemption EARNED rather
    than announced. An earlier cut tested three substrings anywhere in the file, which a
    clean-room pass defeated three ways without touching the launcher at all: change the
    BRAIN's description and never re-sync (the exact forgotten-sync shape this whole check
    exists for) and the launcher still passed, because nothing compared them.
    """
    if GEN not in body or "END TO END" not in body:
        return False
    m = LAUNCH_RE.search(body)
    if not m or m.group(1) != cmd_name:
        return False
    # The engine copies the brain's description into the stub verbatim, so a drifted
    # description IS a drifted door - it is what the Antigravity menu actually displays.
    return fm_field(body, "description") == fm_field(brain, "description")


def platforms_of(text: str) -> tuple[str, ...]:
    """Same parse as sync-agents' Get-CommandPlatforms: absent = universal, [] = nowhere."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return ALL
    for ln in lines[1:60]:
        if ln.strip() == "---":
            break
        m = re.match(r"\s*platforms:\s*\[(.*?)\]", ln)
        if m:
            return tuple(x.strip().strip("\"'").lower() for x in m.group(1).split(",") if x.strip())
    return ALL


def platforms(cmd: Path) -> tuple[str, ...]:
    return platforms_of(read(cmd))


def mirror_place_error(platform: str, pl: tuple[str, ...], present: bool,
                       hand_owned_door: bool) -> bool:
    """Does a mirror door sit on a surface its command does not claim?

    The skill doors have asserted this in BOTH directions since SCC-66 - this file's own header
    says "a door in the wrong place is exactly as wrong as a missing one" - but the two MIRROR
    surfaces only ever asserted the missing direction. Now they assert both.

    ⛔ `hand_owned_door` is the ONE exemption, and it is EARNED by the caller, never announced:
    the engine derives generated doors from `platforms:` and makes no such promise for files in
    `$excluded`, so the exemption applies only while the hand-owned door itself declares the
    surface it is sitting on. See the call site.
    """
    if not present or platform in pl:
        return False
    return not hand_owned_door


def main() -> int:
    c = Cases("command surface contracts")

    cmds = sorted(p for p in (ROOT / ".agents/commands").glob("*.md")
                  if not p.stem.endswith("-AP") and p.name != "INDEX.md")
    master_skills = ROOT / ".agents/skills"
    claude_skills = ROOT / ".claude/skills"

    # ── The retired doors stay retired ────────────────────────────────────────
    stale_cmd_mirror = sorted(p.name for p in (ROOT / ".claude/commands").glob("*.md"))
    c.check("`.claude/commands` is a retired door - no command mirrors there",
            not stale_cmd_mirror,
            f"{len(stale_cmd_mirror)} left: {stale_cmd_mirror[:6]}")

    sync_ps1 = read(ROOT / ".agents/scripts/sync-agents.ps1")

    # The engine's own hand-owned list, read rather than restated (see wf_hand_owned).
    # Pinned non-empty: a regex that stopped matching would exempt NOTHING here, but the same
    # value gates the ghost check below, where an empty set is the SAFE direction and a
    # runaway one is not. Assert it parsed, so a silent parse failure cannot drift either way.
    hand_owned = wf_hand_owned(sync_ps1)
    # Identity, not cardinality. `2 <= len(...) <= 8` encoded TODAY's count as a contract:
    # regenerating both hand-owned workflows and shrinking $excluded to just INDEX.md is a
    # perfectly legitimate future state, and it would have failed with the actively
    # misleading message "not guessed" - when the list had been read correctly.
    # Only INDEX.md is legitimately SOURCELESS - see the ghost check near the end of this file,
    # where the difference between this set and `hand_owned` is load-bearing.
    SOURCELESS = {"INDEX.md"}
    unknown = sorted(n for n in hand_owned
                     if n != "INDEX.md" and not (ROOT / ".agents/workflows" / n).is_file())
    c.check("the hand-owned workflow list was READ from the sync engine, not guessed",
            "INDEX.md" in hand_owned and not unknown,
            f"parsed {sorted(hand_owned)} from $excluded; names with no such workflow: "
            f"{unknown}")

    # ⭐ What makes the hand-owned exemption below EARNED. A file in `$excluded` is exempt from
    # "does its command claim antigravity?" because the engine never derives it from `platforms:`
    # - `smh-adviser-board` declares `[claude, opencode, codex]` yet keeps a hand-authored
    # Antigravity door, and that is correct. But the exemption survives only while the door
    # itself says it belongs here. Parsed with the SAME rule the engine uses (absent = universal),
    # so it fails CLOSED on the shape that matters: a hand-owned workflow declaring
    # `platforms: [claude]` while sitting in Antigravity's surface, exempt from every other check.
    disowned = sorted(n for n in hand_owned - SOURCELESS
                      if (ROOT / ".agents/workflows" / n).is_file()
                      and "antigravity" not in platforms_of(read(ROOT / ".agents/workflows" / n)))
    c.check("every hand-owned workflow declares the surface it sits on",
            not disowned,
            f"{disowned} - excluded from the sync AND from the placement check, so a wrong "
            f"`platforms:` here is invisible to everything else")

    c.check("the sync engine states the door model and both retirements",
            "THE DOOR MODEL" in sync_ps1
            and "codex prompts cache RETIRED" in sync_ps1
            and "Claude's door is .claude\\skills" in sync_ps1,
            "sync-agents.ps1 no longer states the door model + both retirements")

    # ── Every eligible command has EXACTLY ONE door on each platform it claims ─
    missing_skill, wrong_place, bad_body = [], [], []
    missing_oc, missing_ag = [], []
    for cmd in cmds:
        pl = platforms(cmd)
        name = cmd.stem
        in_master = (master_skills / name / "SKILL.md").is_file()
        in_cache = (claude_skills / name / "SKILL.md").is_file()

        if "codex" in pl:
            # Codex reads .agents/skills directly - the door must be in the master.
            if not in_master:
                missing_skill.append(f"{name} (codex)")
            if "claude" not in pl and in_cache:
                wrong_place.append(f"{name}: codex-only but present in .claude/skills")
        if "claude" in pl:
            # Claude's menu reads the cache; a claude-only launcher must NOT sit in the
            # Codex-visible master.
            if not in_cache:
                missing_skill.append(f"{name} (claude)")
            if "codex" not in pl and in_master:
                wrong_place.append(f"{name}: claude-only but present in .agents/skills")

        # Whichever copy exists, a GENERATED launcher must point at its own command body.
        # Shares `is_launcher_for` with the parity sweep below - one rule, one implementation,
        # so the next tightening cannot land in only one of the two places.
        for sk in (master_skills / name / "SKILL.md", claude_skills / name / "SKILL.md"):
            if sk.is_file():
                body = read(sk)
                if GEN in body and not is_launcher_for(body, read(cmd), cmd.name):
                    bad_body.append(str(sk.relative_to(ROOT)))

        # ── The mirror surfaces, BOTH directions ──────────────────────────────
        # Missing was always asserted; misplaced never was. The engine purges a mirror whose
        # command stopped claiming that platform (`Sync-CommandDir`'s `$masterNames` branch;
        # `Sync-AntigravityWorkflowMirror`'s `$stale`), so a misplaced door means the reach
        # changed and NOBODY RAN THE SYNC - which is exactly how SCC-77 shipped stale doors.
        oc_here = (ROOT / ".opencode/commands" / cmd.name).is_file()
        ag_here = (ROOT / ".agents/workflows" / cmd.name).is_file()
        if "opencode" in pl and not oc_here:
            missing_oc.append(name)
        if "antigravity" in pl and not ag_here:
            missing_ag.append(name)
        # hand_owned_door is False for opencode, per-surface like the launcher exemption (A-8):
        # `Sync-CommandDir` has no exclusion list at all - every file it recognises it manages.
        if mirror_place_error("opencode", pl, oc_here, hand_owned_door=False):
            wrong_place.append(f"{name}: does not claim opencode, but .opencode/commands has it")
        # EARNED AT THE POINT OF USE: hand-owned is not enough on its own - the door must also
        # declare this surface. `disowned` above is not redundant with this; it catches the case
        # placement cannot see, where the COMMAND claims antigravity and the door denies it.
        hand_ag = (cmd.name in hand_owned and ag_here
                   and "antigravity" in platforms_of(read(ROOT / ".agents/workflows" / cmd.name)))
        if mirror_place_error("antigravity", pl, ag_here, hand_owned_door=hand_ag):
            wrong_place.append(f"{name}: does not claim antigravity, but .agents/workflows has it")

    c.check("every claude/codex-eligible command has its skill door",
            not missing_skill, f"{len(missing_skill)} missing: {missing_skill[:6]}")

    # Controls for the placement rule, both directions - a sweep that is clean today says
    # nothing about whether the check has teeth.
    OC_ONLY = ("opencode",)
    c.check("door-place CONTROL: a mirror on a claimed surface is fine",
            not mirror_place_error("opencode", OC_ONLY, True, False))
    c.check("door-place CONTROL: a mirror on an UNCLAIMED surface is caught",
            mirror_place_error("antigravity", OC_ONLY, True, False),
            "the reach changed and nobody ran /smh-sync-agents")
    c.check("door-place CONTROL: a hand-owned door on an unclaimed surface is exempt",
            not mirror_place_error("antigravity", OC_ONLY, True, True),
            "smh-adviser-board is real: hand-authored Antigravity door, command claims three "
            "other platforms - and the exemption is earned above, not announced")
    c.check("door-place CONTROL: no door, no error (the condition is not inverted)",
            not mirror_place_error("antigravity", OC_ONLY, False, False))

    c.check("no door sits on a platform its command does not claim",
            not wrong_place, f"{len(wrong_place)}: {wrong_place[:4]}")
    c.check("every generated launcher points at its own command body, END TO END",
            not bad_body, f"{len(bad_body)}: {bad_body[:4]}")
    c.check("every opencode-eligible command has its mirror",
            not missing_oc, f"{len(missing_oc)} missing: {missing_oc[:6]}")
    c.check("every antigravity-eligible command has its workflow mirror (thin launcher counts)",
            not missing_ag, f"{len(missing_ag)} missing: {missing_ag[:6]}")

    # ── Door CONTENT parity (SCC-113 follow-on) ──────────────────────────────
    # Every check above asks whether a door EXISTS. None asks whether it still says what its
    # brain says, and that gap shipped a live break: SCC-77 landed the armed `main` write gate
    # on `main` without running /smh-sync-agents, so `.opencode/commands/` and
    # `.agents/workflows/` kept the pre-token merge steps while MAIN-PUSH-ENFORCE was armed.
    # An opencode or Antigravity agent following them reaches `git push origin main` with no
    # token and is refused, with nothing in its instructions telling it to mint one. Claude and
    # Codex were fine - their doors are thin launchers that read the brain live, which is
    # exactly why the drift was invisible to a human spot-check.
    #
    # SCC-77's close-out reported a fully green floor. This is the check that was missing.

    def door_verdict(brain: str, body: str, cmd_name: str, launcher_ok: bool) -> str:
        """'ok' | 'stale' | 'badlauncher' - for ONE mirror door against its command body.

        A mirror is one of exactly two legal things:
          * a FULL MIRROR, byte-identical to the brain; or
          * a THIN LAUNCHER - but ONLY on `.agents/workflows`, and only a current one.

        ⛔ `launcher_ok` is passed per-surface because **opencode has no launcher form.**
        `Sync-CommandDir` is `Copy-Item -Force` and nothing else; the launcher branch exists
        solely in `Sync-AntigravityWorkflowMirror`, for Antigravity's 12k cap. Offering the
        exemption to an opencode door let a 9 KB shipping command be replaced by a 9-line
        pointer with the suite green - an opencode agent invoking it would get a signpost
        instead of the gate-and-merge steps.
        """
        if body == brain:
            return "ok"
        if launcher_ok and is_launcher_for(body, brain, cmd_name):
            return "ok"
        if GEN in body:
            return "badlauncher"   # claims to be generated, but is not a current launcher
        return "stale"

    # Controls first, as pure string cases - the live sweep below can only ever prove the
    # tree is currently clean, which is not the same as proving the check has teeth.
    BRAIN = "---\ndescription: Do the thing.\nplatforms: [antigravity]\n---\n# /x\n\nbody\n"
    LAUNCHER = ("---\ndescription: Do the thing.\n---\n"
                "# /x - launcher (GENERATED by sync-agents; do not edit)\n"
                "**Execute now:** read `.agents/commands/x.md` and follow it END TO END\n")
    WF, OC = True, False          # launcher form exists on workflows only

    c.check("door-parity CONTROL: an identical mirror is ok",
            door_verdict(BRAIN, BRAIN, "x.md", WF) == "ok")
    c.check("door-parity CONTROL: a STALE mirror is caught",
            door_verdict(BRAIN, BRAIN.replace("body", "old body"), "x.md", WF) == "stale",
            "this is the SCC-77 shape - a door that still reads the pre-change steps")
    c.check("door-parity CONTROL: a truncated mirror is caught",
            door_verdict(BRAIN, "---\ndescription: Do the thing.\n---\n# /x\n", "x.md", WF)
            == "stale")
    c.check("door-parity CONTROL: a current thin launcher is exempt",
            door_verdict(BRAIN, LAUNCHER, "x.md", WF) == "ok")

    # ⭐ The three shapes a clean-room pass used to defeat the FIRST cut of this exemption,
    # which tested three substrings appearing anywhere in the file.
    c.check("door-parity CONTROL: a launcher whose BRAIN's description moved on is caught",
            door_verdict(BRAIN.replace("Do the thing.", "RETIRED - use /y instead."),
                         LAUNCHER, "x.md", WF) == "badlauncher",
            "the forgotten-sync shape: nobody touched the launcher, and it is now lying to "
            "the Antigravity menu about what this command does")
    c.check("door-parity CONTROL: a launcher REPOINTED at another brain is caught, even "
            "with the old path still present in a comment",
            door_verdict(BRAIN,
                         "<!-- generated from .agents/commands/x.md -->\n"
                         + LAUNCHER.replace("read `.agents/commands/x.md`",
                                            "read `.agents/commands/other.md`"),
                         "x.md", WF) == "badlauncher",
            "a substring test reads the stale COMMENT as the pointer - the exact "
            "comment-literals-invert-source-grep-tests inversion")
    c.check("door-parity CONTROL: the marker alone does NOT excuse drift",
            door_verdict(BRAIN, "# GENERATED by sync-agents\nanything at all\n", "x.md", WF)
            == "badlauncher")

    # opencode has no launcher form at all - Copy-Item, or it is wrong.
    c.check("door-parity CONTROL: a launcher on an OPENCODE door is NOT exempt",
            door_verdict(BRAIN, LAUNCHER, "x.md", OC) == "badlauncher",
            "the engine never emits a launcher there; a pointer would replace the steps")

    # ⭐ REGRESSION CONTROL — the real historical defect, not a shape I imagined.
    # `ea8fe97` is the commit that re-synced the doors SCC-77 left stale; its parent holds the
    # genuinely stale `.opencode/commands/cicd-push-e2e.md` (8464b, zero mint-push-token
    # references) that the pre-SCC-113 gate passed 13/13. Every other control here is a string
    # I wrote, which only ever proves the check does what I expected it to.
    # Degrades LOUDLY, never silently: with no history reachable it synthesizes an equivalent
    # stale door and says so in the message, so the control always runs.
    hist = subprocess.run(["git", "show", "ea8fe97^:.opencode/commands/cicd-push-e2e.md"],
                          cwd=ROOT, capture_output=True, text=True)
    pushe2e = read(ROOT / ".agents/commands/cicd-push-e2e.md")
    if hist.returncode == 0 and hist.stdout.strip():
        stale_door, src = hist.stdout, "the REAL pre-ea8fe97 bytes"
    else:
        stale_door, src = pushe2e.split("## Step 6")[0], "a synthesized stale door (no history)"
    c.check(f"door-parity REGRESSION CONTROL fires on {src}",
            door_verdict(pushe2e, stale_door, "cicd-push-e2e.md", launcher_ok=False)
            == "stale",
            "the gate reported 13/13 green on exactly this file - that is the whole reason "
            "this check exists")

    MIRRORS = (".opencode/commands", ".agents/workflows")
    drifted, examined = [], 0
    for cmd in cmds:
        brain = read(cmd)
        for rel in MIRRORS:
            # A hand-owned workflow is authored, not generated, and legitimately differs from
            # its brain — `smh-adviser-board` is a condensed 2 KB Antigravity variant of a
            # 52 KB command. The engine never writes these, so parity is not the contract.
            if rel == ".agents/workflows" and cmd.name in hand_owned:
                continue
            door = ROOT / rel / cmd.name
            if not door.is_file():
                continue
            examined += 1
            v = door_verdict(brain, read(door), cmd.name,
                             launcher_ok=(rel == ".agents/workflows"))
            if v != "ok":
                drifted.append(f"{rel}/{cmd.name} [{v}]")

    c.check("every mirror door still says what its brain says",
            not drifted,
            f"{len(drifted)} drifted - run /smh-sync-agents: {drifted[:6]}")

    # ⭐ An empty sweep is indistinguishable from a clean one, and "0 offenders" out of 0 doors
    # is the vacuous green `tests-must-gate-for-real` names. A renamed cache directory or a
    # typo'd glob would otherwise read as a pass forever.
    c.check("door-parity examined a real number of doors (not a silent empty sweep)",
            examined >= 40, f"only {examined} mirror doors examined")

    # ── Positive control: the generator must actually be generating ───────────
    # Without this, every check above passes trivially if the emit stage silently no-ops.
    generated = [d.name for d in master_skills.iterdir()
                 if (d / "SKILL.md").is_file() and GEN in read(d / "SKILL.md")]
    c.check("the launcher generator produced doors (not a silent no-op)",
            len(generated) >= 10, f"only {len(generated)} generated launchers")

    # ── Hand-authored skills are never overwritten by the generator ───────────
    # These carry real content (boundaries, routing notes) a stub would destroy.
    hand = ["cicd-park", "cicd-resume", "cicd-close-workingtree", "smh-close-task-merge-tree",
            "cicd-update-sprint-memory", "smh-update-maps-indexes"]
    clobbered = [n for n in hand
                 if (master_skills / n / "SKILL.md").is_file()
                 and GEN in read(master_skills / n / "SKILL.md")]
    c.check("hand-authored skills survive a sync untouched",
            not clobbered, f"overwritten by the generator: {clobbered}")

    # ── Every skill door is loadable: frontmatter with a description ──────────
    no_fm = []
    for d in sorted(master_skills.iterdir()):
        sk = d / "SKILL.md"
        if not sk.is_file():
            continue
        head = read(sk)[:1200]
        if not head.startswith("---") or "description:" not in head:
            no_fm.append(d.name)
    c.check("every skill door carries frontmatter with a description",
            not no_fm, f"{len(no_fm)}: {no_fm[:6]}")

    # ── Stale mirrors: a door with no command source is a ghost ───────────────
    cmd_names = {p.name for p in (ROOT / ".agents/commands").glob("*.md")}
    # ⛔ The ghost exemption is NOT `hand_owned`, and the difference is load-bearing. Only
    # `INDEX.md` is legitimately SOURCELESS; the other two hand-owned workflows are variants
    # OF a command and must keep having one. Exempting them here (as a first cut did, by
    # reusing `hand_owned`) made this check go silent on the one shape it most needs to
    # catch - a hand-authored launcher left pointing at a brain that was deleted. Verified:
    # delete `.agents/commands/smh-adviser-board.md` and the loose version reports 0 ghosts.
    wf_present = sorted(p.name for p in (ROOT / ".agents/workflows").glob("*.md"))
    ghosts = [n for n in wf_present if n not in cmd_names and n not in SOURCELESS]
    c.check("no ghost workflow mirrors (every one has a command source)",
            not ghosts, f"{len(ghosts)}: {ghosts[:6]}")
    orphaned_hand = sorted(n for n in hand_owned - SOURCELESS if n not in cmd_names)
    c.check("every hand-owned workflow still has the command it is a variant of",
            not orphaned_hand,
            f"{orphaned_hand} - excluded from the sync, so nothing else would notice")

    # ⭐ The SAME check for opencode, which never had one - and here it is not a backstop, it is
    # the ONLY thing that would ever notice. `Sync-CommandDir` runs for opencode WITHOUT
    # `-Mirror` (sync-agents.ps1:821), and its purge branch ends
    # `else { $false }  # local: keep foreign/project-own files`. Delete a command brain and its
    # opencode door is not eligible, no longer in `$masterNames`, and not a mirror - it falls to
    # that final `$false` and is kept FOREVER, still offering an opencode agent a retired flow.
    # The workflows mirror prunes, which is why that side has been guarded all along.
    oc_present = sorted(p.name for p in (ROOT / ".opencode/commands").glob("*.md"))
    oc_ghosts = [n for n in oc_present if n not in cmd_names]
    c.check("no ghost opencode mirrors (every one has a command source)",
            not oc_ghosts,
            f"{len(oc_ghosts)}: {oc_ghosts[:6]} - the opencode sync KEEPS these; only this "
            f"check will ever say so")

    # Both sweeps get A-3's guard: "0 ghosts" out of 0 files read is the vacuous green, and a
    # renamed cache directory is exactly how you get one. Today: 34 workflows, 53 opencode.
    c.check("the ghost sweeps read a real number of doors (not two empty directories)",
            len(wf_present) >= 20 and len(oc_present) >= 40,
            f"workflows={len(wf_present)} opencode={len(oc_present)} - a glob resolved to "
            f"nothing, so every ghost check above passed on an empty set")

    # ── The docs agree with the engine ────────────────────────────────────────
    agents_md = read(ROOT / "AGENTS.md")
    c.check("root AGENTS.md documents the door model for every platform",
            "one door per platform per command" in agents_md.lower()
            and "launcher skill" in agents_md,
            "AGENTS.md no longer documents the door model")
    sync_cmd = read(ROOT / ".agents/commands/smh-sync-agents.md")
    c.check("sync-agents command doc names both retired doors",
            "RETIRED door" in sync_cmd and "/prompts:<name>" in sync_cmd
            and "Do not use `-Maintained`" in sync_cmd,
            "smh-sync-agents.md no longer matches what the engine does")

    return c.finish()


if __name__ == "__main__":
    raise SystemExit(main())
