"""One door per platform per command (SCC-66) — the contract that keeps four menus honest.

Command docs, skill launchers, sync instructions and the actual on-disk caches used to be four
independent claims about the same thing, and they disagreed: 19 commands published BOTH a
`.claude/commands` mirror and a skill, Codex carried a deprecated `/prompts:` twin beside its
native skill, and the only way to notice was for a human to open a menu and find it wrong. That
is what burned the failed session this program came from.

The door model, and why it is forced rather than chosen:
  * Codex cannot expose repo-defined top-level `/name` commands at all — skills are its ONLY door;
  * Claude Code publishes a slash command for every `.claude/skills/*/SKILL.md` — so a skill is
    already a Claude door, and a command mirror beside it is a second one;
  * therefore ONE launcher skill serves Claude and Codex both, and `.claude/commands` +
    `~/.codex/prompts` are retired. opencode keeps its command mirror; Antigravity its workflow
    mirror (thin launcher when the body clears its 12k cap).

Reach comes from `platforms:` frontmatter (absent = universal), which splits the skill door two
ways: `.agents/skills` is Codex's NATIVE surface, so a claude-only command's launcher must live in
the `.claude/skills` cache only, and a codex-only command's launcher must be kept OUT of that cache.
Both directions are asserted — a door in the wrong place is exactly as wrong as a missing one.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

from _harness import Cases, TempDir

import wf_common as wf          # noqa: E402  (_harness put SCRIPTS on sys.path)
import workflow_lint as lint    # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
ALL = ("claude", "opencode", "antigravity", "codex")
GEN = "GENERATED by sync-agents"

def parse_own_list(text: str) -> set[str]:
    """SCC-113: `.agents/project-own.txt`, parsed the way the ENGINE parses it.

    PowerShell (`Get-OwnAllowList`, sync-agents.ps1:310): `($_ -replace '#.*$','').Trim()`, then
    drop empties. Two parsers of one fact must agree, because a parser more generous than the
    engine's would exempt a door the engine still purges — and the keep-list only means anything
    while both sides agree about what survives a sync.

    ⭐ Agreement includes CASE. PowerShell's `-contains` (`:872`) is case-insensitive, so the
    engine keeps `Smh-Review.md` for a list saying `smh-review.md`; a case-sensitive mirror here
    would call that same door a ghost. Callers fold — see `ghost_doors`. (A BOM needs no handling:
    every caller reads through `read()`, which is `utf-8-sig`.)

    NAMES ONLY, never patterns. `*` parses to the literal filename `*`, which matches nothing on
    disk, so a malformed or hopeful list cannot widen the exemption to everything.
    """
    names = set()
    for raw in text.splitlines():
        name = raw.split("#", 1)[0].strip()
        if name:
            names.add(name)
    return names


def ghost_doors(present: list[str], sources: set[str],
                claimed: frozenset[str] = frozenset()) -> list[str]:
    """SCC-113: doors with no command source and no keep-list claim.

    EXACT names, never substrings — a prefix match would let one claim cover every sibling door.
    Case-folded on both sides, because every membership test this mirrors is a PowerShell
    `-contains`, which is case-insensitive (see `parse_own_list`).
    """
    src = {s.casefold() for s in sources}
    kept = {c.casefold() for c in claimed}
    return [n for n in present if n.casefold() not in src and n.casefold() not in kept]


def wf_hand_owned(sync_ps1: str) -> set[str]:
    """workflows/ files the sync engine deliberately never writes — read FROM the engine.

    ⭐ Derived, not restated. This was `{"INDEX.md"}`: a hand-copied subset of the engine's
    three-entry `$excluded`, missing `smh-update-maps-indexes.md` and `smh-adviser-board.md`,
    which are hand-authored Antigravity workflows that legitimately differ from their command
    bodies (one is a condensed 2 KB variant of a 52 KB brain; the other is a 40 KB doc whose
    brain was later rewritten to 4 KB). The door-parity check below reported both as drift on
    its first run — a false positive caused entirely by the duplicated list.

    Two parsers of one fact must agree, so this reads the fact instead of copying it. A parse
    that returns nothing fails SAFE (nothing is exempted, so the sweep gets noisier, never
    quieter); the assertion in main() pins that it parsed at all.

    ⛔ ANCHORED to the function that owns it. An unscoped search takes the FIRST
    `$excluded = @(...)` in a 900-line file - and the file already has `$ExcludeDirs` /
    `$ExcludeFiles` in nearby scope, so a same-named local is not exotic. A clean-room pass
    defeated the unscoped version by adding an earlier array carrying one extra name: the
    ghost check then went silent on a genuinely orphaned workflow and the suite stayed green.
    OVERBROAD is the one direction that fails OPEN, which is why the scope is not optional.
    """
    start = sync_ps1.find("function Sync-AntigravityWorkflowMirror")
    m = re.search(r"\$excluded\s*=\s*@\(([^)]*)\)",
                  sync_ps1[start:] if start != -1 else sync_ps1)
    return set(re.findall(r"'([^']+)'", m.group(1))) if m else set()


def read(p: Path) -> str:
    # utf-8-SIG, not utf-8: 8 testarch-* commands carry a UTF-8 BOM. PowerShell's ReadAllLines
    # strips it, so sync-agents reads their `platforms: [opencode]` correctly - a plain utf-8 read
    # here leaves `﻿---` on line 1, which str.strip() does NOT remove (U+FEFF is not Python
    # whitespace), so the frontmatter probe misses and every one of them reads as UNIVERSAL. The
    # test then demands Claude/Codex/Antigravity doors for eight opencode-only bridges. Two parsers
    # of one file must agree byte-for-byte or the gate invents work.
    return p.read_text(encoding="utf-8-sig", errors="replace")


def fm_field(text: str, key: str) -> str | None:
    """A frontmatter scalar, or None. Used to compare a launcher against its brain."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for ln in lines[1:80]:
        if ln.strip() == "---":
            break
        if ln.startswith(f"{key}:"):
            return ln[len(key) + 1:].strip()
    return None


# The launcher's ONE instruction. Anchored to `read `…`` on purpose: a bare "does the path
# appear anywhere" test is satisfied by a stale `<!-- generated from … -->` comment sitting
# above a pointer that now names a DIFFERENT command - the repo's own
# comment-literals-invert-source-grep-tests lesson, reproduced against this very check.
LAUNCH_RE = re.compile(r"read\s+`\.agents/commands/([A-Za-z0-9._-]+\.md)`")


# ── SCC-195 · the Antigravity DESCRIPTION BUDGET ───────────────────────────────────────────
#
# Antigravity builds its slash-command menu from the `description:` frontmatter of every
# `.agents/workflows/*.md`. This repo's descriptions run 400-950+ characters (they are written
# for an agent reading the command, not for a menu), and the total blew the menu's context
# budget: **15 workflows were dropped from the agent's command list outright.**
#
# ⛔ AND THE OBVIOUS FIX WAS ALREADY BLOCKED, WHICH IS THE ACTUAL TICKET. Shortening the
# descriptions BY HAND in `.agents/workflows/` cannot work twice over: the files are GENERATED,
# so the next `/smh-sync-agents` overwrites them; and this file's own door-parity check demands
# the mirror be byte-identical to its brain (or a launcher whose description EQUALS the
# brain's), so a hand-shortened door reads as `stale` and the main-write-gate goes red.
# `origin/chore/SCC-194-workflow-titles` is exactly that attempt, 34 files, unlandable by
# construction.
#
# So the shortening moves INTO the generator, and this check learns the same rule: the
# Antigravity door carries a TRUNCATED description, and truncated-from-the-brain is parity.
# Two implementations of one rule (PowerShell emits, Python verifies) - which is the shape this
# file already has for `platforms:` (`Get-CommandPlatforms` vs `platforms_declared`), and the
# reason the check is a REAL comparison rather than a length test: if the two ever disagree the
# door reads `stale` and names the file.
AG_DESC_MAX = 135
AG_DESC_CUT = 132


def ag_description(desc: str) -> str:
    """The description as Antigravity's menu should carry it. Idempotent on a short one.

    Word-boundary cut, then an ASCII ellipsis - never mid-word, and never a non-ASCII character
    (the PowerShell side writes these literals from a BOM-less .ps1 that PS 5.1 parses as ANSI,
    so a real `…` would ship as mojibake in every generated file).

    ⛔ UTF-16 UNITS, BECAUSE THE GENERATOR IS .NET. `$Desc.Length`, `.Substring` and
    `.LastIndexOf` all index UTF-16 code units; Python's `len`/slicing index CODE POINTS, and
    the two agree only while every character is in the BMP. A single astral character (an emoji
    in a description) makes PowerShell cut at 90 code points where this cut at 132 - the door
    then reads `stale`, and because the file is GENERATED the operator cannot fix it by hand.
    That is the SCC-194 wedge rebuilt, so this emulates the generator rather than the language
    it happens to be written in. (Measured by the test-adequacy audit: the two agree on all 55
    live descriptions and diverge the moment one carries a non-BMP character.)"""
    b = desc.encode("utf-16-le")
    if len(b) // 2 <= AG_DESC_MAX:
        return desc
    # `errors="ignore"` covers the one shape .NET and Python genuinely cannot agree on: a cut
    # landing INSIDE a surrogate pair. .NET keeps the orphan half (an invalid string); this
    # drops it. The word-boundary trim below removes it in every realistic case anyway, and
    # neither implementation should be shipping a lone surrogate into a menu.
    cut = b[:AG_DESC_CUT * 2].decode("utf-16-le", errors="ignore")
    if " " in cut:
        cut = cut[:cut.rindex(" ")]
    return cut.rstrip(" ,;:-") + "..."


def with_ag_description(brain: str) -> str:
    """The brain with ONLY its `description:` line replaced by the budgeted one."""
    out, done = [], False
    for line in brain.splitlines(keepends=True):
        if not done and line.startswith("description:"):
            # The line's OWN terminator, preserved: `.strip()` eats a CR, and re-appending a
            # bare "\n" would turn one line of a CRLF brain into an LF line. Same fix, same
            # reason, as `Set-AgDescriptionLine` in sync-agents.ps1 - these two are twins and
            # a divergence here is a divergence in what the generator is claimed to do.
            body = line[len("description:"):]
            nl = body[len(body.rstrip("\r\n")):]
            out.append("description: " + ag_description(body.strip()) + nl)
            done = True
        else:
            out.append(line)
    return "".join(out)


def is_launcher_for(body: str, brain: str, cmd_name: str, budgeted: bool = False) -> bool:
    """Is `body` the generated thin launcher for THIS command, still current?

    ⭐ Four conditions, and the third and fourth are what make the exemption EARNED rather
    than announced. An earlier cut tested three substrings anywhere in the file, which a
    clean-room pass defeated three ways without touching the launcher at all: change the
    BRAIN's description and never re-sync (the exact forgotten-sync shape this whole check
    exists for) and the launcher still passed, because nothing compared them.
    """
    if GEN not in body or "END TO END" not in body:
        return False
    m = LAUNCH_RE.search(body)
    if not m or m.group(1) != cmd_name:
        return False
    # The engine copies the brain's description into the stub, so a drifted description IS a
    # drifted door - it is what the Antigravity menu actually displays.
    #
    # ⛔ `budgeted` IS PER-SURFACE, and conflating the two surfaces is a real defect this check
    # caught on itself: SCC-195's budget is ANTIGRAVITY's menu constraint. The Claude/Codex
    # launcher skills (`New-LauncherSkillStub`) carry the brain's FULL description and must keep
    # doing so - applying the cut to them turned 39 correct doors red in one edit.
    want = fm_field(brain, "description") or ""
    return fm_field(body, "description") == (ag_description(want) if budgeted else want)


def platforms_declared(text: str) -> tuple[str, ...] | None:
    """The EXPLICIT `platforms:` list, or **None when the key is absent**.

    ⭐ SCC-113 split this out of `platforms_of` because two callers need opposite readings of
    silence, and collapsing them let one of those callers pass on nothing at all:

      * deriving a GENERATED door from a command — absent means UNIVERSAL. That is the engine's
        rule (`Get-CommandPlatforms`, sync-agents.ps1:423) and `platforms_of` keeps it. ⚠ Two
        known divergences from it, both QUEUED and both failing SAFE (this parser is the
        stricter one, so it over-demands doors rather than missing them): the scan here stops at
        `lines[1:60]` and the engine has no cap, and PowerShell's `-match` is case-insensitive
        where this is not. Named because a lane about checks that overclaim does not get to
        write "that is the engine's rule" and leave the exceptions unsaid.
      * the HAND-OWNED door exemption — the exemption turns on the door ASSERTING that it
        belongs on the surface it sits on. A file with no `platforms:` key asserts nothing, and
        an exemption earned by silence is announced, not earned. `[]` is different: it is a real
        claim (of nowhere), so it returns `()` and correctly fails the antigravity test.

    One parse, two readings — so the next tightening cannot land in only one of them.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for ln in lines[1:60]:
        if ln.strip() == "---":
            break
        m = re.match(r"\s*platforms:\s*\[(.*?)\]", ln)
        if m:
            return tuple(x.strip().strip("\"'").lower()
                         for x in m.group(1).split(",") if x.strip())
    return None


def platforms_of(text: str) -> tuple[str, ...]:
    """Same parse as sync-agents' Get-CommandPlatforms: absent = universal, [] = nowhere."""
    declared = platforms_declared(text)
    return ALL if declared is None else declared


def claims_explicitly(text: str, platform: str) -> bool:
    """Does this file SAY it belongs on `platform`? Silence is not a claim."""
    declared = platforms_declared(text)
    return declared is not None and platform in declared


def platforms(cmd: Path) -> tuple[str, ...]:
    return platforms_of(read(cmd))


def mirror_place_error(platform: str, pl: tuple[str, ...], present: bool,
                       hand_owned_door: bool) -> bool:
    """Does a mirror door sit on a surface its command does not claim?

    The skill doors have asserted this in BOTH directions since SCC-66 - this file's own header
    says "a door in the wrong place is exactly as wrong as a missing one" - but the two MIRROR
    surfaces only ever asserted the missing direction. Now they assert both.

    ⛔ `hand_owned_door` is the ONE exemption, and it is EARNED by the caller, never announced:
    the engine derives generated doors from `platforms:` and makes no such promise for files in
    `$excluded`, so the exemption applies only while the hand-owned door itself declares the
    surface it is sitting on. See the call site.
    """
    if not present or platform in pl:
        return False
    return not hand_owned_door


def rif_block(text: str) -> str:
    """The `> **Rules in force for this command:**` blockquote, or `""` when there is none.

    ⛔ BLOCK-SCOPED, and that scoping IS the check (SCC-145). A command can name a rule anywhere
    in 400 lines of prose — a step body, an aside, an example — and a file-wide `in` test reads
    every one of those as "the rule is loaded." It is not. The rules-in-force block is what an
    agent reads as standing law **before Step 0**; a citation buried in step prose arrives after
    the decision it governs. Measured: `/smh-code-review` carries the mutation rule in its block,
    `/cicd-clean-code-audit` cites it twice in step prose and never loaded it. A file-grep calls
    those two the same, which is `prose-pinning-guards-are-vacuous` in the guard itself.

    Returns `""` for a file with no block, so callers fail CLOSED — a command that dropped its
    whole block must go red, never pass quietly on an empty search space.
    """
    lines = text.splitlines()
    start = next((i for i, ln in enumerate(lines)
                  if "Rules in force for this command" in ln), None)
    if start is None:
        return ""
    out = []
    for ln in lines[start:]:
        if not ln.lstrip().startswith(">"):   # a blank line ends a blockquote in markdown too
            break
        out.append(ln)
    return "\n".join(out)


def md_section(text: str, heading_rx: str) -> str:
    """One `##`-level section — its heading through to the next `## ` — or `""` when absent.

    ⛔ Anchored to the HEADING, never to the body, and the difference is the whole reason this
    exists. `tests-must-gate-for-real.md` has carried the word "mutation" since the day it was
    written — twice, at lines 76-77, inside `## Why`, narrating an old AGY story — while the
    practice itself was an unnamed fourth sub-bullet under a rule headlined about certification
    SHAs. A body search for the word was satisfied by that provenance passage, so it would have
    reported the doctrine "documented" for as long as the file has existed.

    ⛔ Bounded at the next `## ` because a source-grep guard CANNOT SEE ORDER
    (`source-grep-guards-cannot-see-order`): the mutant-table obligation pinned file-wide stays
    green when it drifts into Step 2, where it fires before the assertions it governs are
    written — re-creating the exact defect SCC-145 exists to close, inside the guard meant to
    prevent it.
    """
    rx = re.compile(heading_rx, re.I)
    lines = text.splitlines()
    start = next((i for i, ln in enumerate(lines) if rx.search(ln)), None)
    if start is None:
        return ""
    out = [lines[start]]
    for ln in lines[start + 1:]:
        if ln.startswith("## "):
            break
        out.append(ln)
    return "\n".join(out)


def main() -> int:
    c = Cases("command surface contracts")

    cmds = sorted(p for p in (ROOT / ".agents/commands").glob("*.md")
                  if not p.stem.endswith("-AP") and p.name != "INDEX.md")
    master_skills = ROOT / ".agents/skills"
    claude_skills = ROOT / ".claude/skills"

    sync_ps1 = read(ROOT / ".agents/scripts/sync-agents.ps1")

    # The engine's own hand-owned list, read rather than restated (see wf_hand_owned).
    # Pinned non-empty: a regex that stopped matching would exempt NOTHING here, but the same
    # value gates the ghost check below, where an empty set is the SAFE direction and a
    # runaway one is not. Assert it parsed, so a silent parse failure cannot drift either way.
    hand_owned = wf_hand_owned(sync_ps1)
    # Identity, not cardinality. `2 <= len(...) <= 8` encoded TODAY's count as a contract:
    # regenerating both hand-owned workflows and shrinking $excluded to just INDEX.md is a
    # perfectly legitimate future state, and it would have failed with the actively
    # misleading message "not guessed" - when the list had been read correctly.
    # Only INDEX.md is legitimately SOURCELESS - see the ghost check near the end of this file,
    # where the difference between this set and `hand_owned` is load-bearing.
    SOURCELESS = {"INDEX.md"}

    if c.block("CS-01 · the retired doors stay retired"):
        # ── The retired doors stay retired ────────────────────────────────────────
        stale_cmd_mirror = sorted(p.name for p in (ROOT / ".claude/commands").glob("*.md"))
        c.check("`.claude/commands` is a retired door - no command mirrors there",
                not stale_cmd_mirror,
                f"{len(stale_cmd_mirror)} left: {stale_cmd_mirror[:6]}")

        unknown = sorted(n for n in hand_owned
                         if n != "INDEX.md" and not (ROOT / ".agents/workflows" / n).is_file())
        c.check("the hand-owned workflow list was READ from the sync engine, not guessed",
                "INDEX.md" in hand_owned and not unknown,
                f"parsed {sorted(hand_owned)} from $excluded; names with no such workflow: "
                f"{unknown}")

        # ⭐ What makes the hand-owned exemption below EARNED. A file in `$excluded` is exempt from
        # "does its command claim antigravity?" because the engine never derives it from `platforms:`
        # - `smh-adviser-board` declares `[claude, opencode, codex]` yet keeps a hand-authored
        # Antigravity door, and that is correct. But the exemption survives only while the door
        # itself says it belongs here. Parsed with the SAME rule the engine uses (absent = universal),
        # so it fails CLOSED on the shape that matters: a hand-owned workflow declaring
        # `platforms: [claude]` while sitting in Antigravity's surface, exempt from every other check.
        # ⭐ SCC-113 tightened this from `platforms_of` to `claims_explicitly`. Under the old
        # reading a hand-owned door with NO `platforms:` key parsed as universal, so antigravity was
        # "declared" — and the exemption was earned by saying nothing at all. That is the same
        # announced-not-earned shape A-2′ already cost this ticket a lane, in the check written to
        # prevent it. Silence now fails, and `platforms: []` still fails (a real claim of nowhere).
        disowned = sorted(n for n in hand_owned - SOURCELESS
                          if (ROOT / ".agents/workflows" / n).is_file()
                          and not claims_explicitly(read(ROOT / ".agents/workflows" / n),
                                                    "antigravity"))
        c.check("every hand-owned workflow EXPLICITLY declares the surface it sits on",
                not disowned,
                f"{disowned} - excluded from the sync AND from the placement check, so a wrong or "
            f"absent `platforms:` here is invisible to everything else")

        # Controls for the two readings of silence — pure strings, no disk. These are what stop the
        # split above from quietly collapsing back into one rule.
        c.check("declaration: silence is NOT a claim (the hand-owned exemption must be spoken)",
                platforms_declared("---\nname: x\ndescription: y\n---\n") is None
                and not claims_explicitly("---\nname: x\n---\n", "antigravity"),
                "a door with no platforms: key asserts nothing and must not be exempt")
        c.check("declaration: an explicit list is read, and only it earns the exemption",
                claims_explicitly("---\nplatforms: [antigravity]\n---\n", "antigravity")
                and not claims_explicitly("---\nplatforms: [claude]\n---\n", "antigravity"),
                "the door must name the surface it is sitting on")
        c.check("declaration: `platforms: []` is a real claim of NOWHERE, not silence",
                platforms_declared("---\nplatforms: []\n---\n") == ()
                and not claims_explicitly("---\nplatforms: []\n---\n", "antigravity"),
                "[] means nowhere; it must fail the claim, not read as absent")
        c.check("declaration: COMMANDS keep the engine's rule - absent still means universal",
                platforms_of("---\nname: x\n---\n") == ALL
                and platforms_of("---\nplatforms: []\n---\n") == (),
                "NEGATIVE CONTROL - tightening the exemption must not change door derivation")

        c.check("the sync engine states the door model and both retirements",
                "THE DOOR MODEL" in sync_ps1
                and "codex prompts cache RETIRED" in sync_ps1
                and "Claude's door is .claude\\skills" in sync_ps1,
                "sync-agents.ps1 no longer states the door model + both retirements")

    if c.block("CS-02 · one door per platform, on every platform the command claims"):
        # ── Every eligible command has EXACTLY ONE door on each platform it claims ─
        missing_skill, wrong_place, bad_body = [], [], []
        missing_oc, missing_ag = [], []
        for cmd in cmds:
            pl = platforms(cmd)
            name = cmd.stem
            in_master = (master_skills / name / "SKILL.md").is_file()
            in_cache = (claude_skills / name / "SKILL.md").is_file()

            if "codex" in pl:
                # Codex reads .agents/skills directly - the door must be in the master.
                if not in_master:
                    missing_skill.append(f"{name} (codex)")
                if "claude" not in pl and in_cache:
                    wrong_place.append(f"{name}: codex-only but present in .claude/skills")
            if "claude" in pl:
                # Claude's menu reads the cache; a claude-only launcher must NOT sit in the
                # Codex-visible master.
                if not in_cache:
                    missing_skill.append(f"{name} (claude)")
                if "codex" not in pl and in_master:
                    wrong_place.append(f"{name}: claude-only but present in .agents/skills")

            # Whichever copy exists, a GENERATED launcher must point at its own command body.
            # Shares `is_launcher_for` with the parity sweep below - one rule, one implementation,
            # so the next tightening cannot land in only one of the two places.
            for sk in (master_skills / name / "SKILL.md", claude_skills / name / "SKILL.md"):
                if sk.is_file():
                    body = read(sk)
                    if GEN in body and not is_launcher_for(body, read(cmd), cmd.name):
                        bad_body.append(str(sk.relative_to(ROOT)))

            # ── The mirror surfaces, BOTH directions ──────────────────────────────
            # Missing was always asserted; misplaced never was. The engine purges a mirror whose
            # command stopped claiming that platform (`Sync-CommandDir`'s `$masterNames` branch;
            # `Sync-AntigravityWorkflowMirror`'s `$stale`), so a misplaced door means the reach
            # changed and NOBODY RAN THE SYNC - which is exactly how SCC-77 shipped stale doors.
            oc_here = (ROOT / ".opencode/commands" / cmd.name).is_file()
            ag_here = (ROOT / ".agents/workflows" / cmd.name).is_file()
            if "opencode" in pl and not oc_here:
                missing_oc.append(name)
            if "antigravity" in pl and not ag_here:
                missing_ag.append(name)
            # hand_owned_door is False for opencode, per-surface like the launcher exemption (A-8):
            # `Sync-CommandDir` has no exclusion list at all - every file it recognises it manages.
            if mirror_place_error("opencode", pl, oc_here, hand_owned_door=False):
                wrong_place.append(f"{name}: does not claim opencode, but .opencode/commands has it")
            # EARNED AT THE POINT OF USE: hand-owned is not enough on its own - the door must also
            # declare this surface. `disowned` above is not redundant with this; it catches the case
            # placement cannot see, where the COMMAND claims antigravity and the door denies it.
            hand_ag = (cmd.name in hand_owned and ag_here
                       and claims_explicitly(read(ROOT / ".agents/workflows" / cmd.name),
                                             "antigravity"))
            if mirror_place_error("antigravity", pl, ag_here, hand_owned_door=hand_ag):
                wrong_place.append(f"{name}: does not claim antigravity, but .agents/workflows has it")

        c.check("every claude/codex-eligible command has its skill door",
                not missing_skill, f"{len(missing_skill)} missing: {missing_skill[:6]}")

        # Controls for the placement rule, both directions - a sweep that is clean today says
        # nothing about whether the check has teeth.
        OC_ONLY = ("opencode",)
        c.check("door-place CONTROL: a mirror on a claimed surface is fine",
                not mirror_place_error("opencode", OC_ONLY, True, False))
        c.check("door-place CONTROL: a mirror on an UNCLAIMED surface is caught",
                mirror_place_error("antigravity", OC_ONLY, True, False),
                "the reach changed and nobody ran /smh-sync-agents")
        c.check("door-place CONTROL: a hand-owned door on an unclaimed surface is exempt",
                not mirror_place_error("antigravity", OC_ONLY, True, True),
                "smh-adviser-board is real: hand-authored Antigravity door, command claims three "
            "other platforms - and the exemption is earned above, not announced")
        c.check("door-place CONTROL: no door, no error (the condition is not inverted)",
                not mirror_place_error("antigravity", OC_ONLY, False, False))

        c.check("no door sits on a platform its command does not claim",
                not wrong_place, f"{len(wrong_place)}: {wrong_place[:4]}")
        c.check("every generated launcher points at its own command body, END TO END",
                not bad_body, f"{len(bad_body)}: {bad_body[:4]}")
        c.check("every opencode-eligible command has its mirror",
                not missing_oc, f"{len(missing_oc)} missing: {missing_oc[:6]}")
        c.check("every antigravity-eligible command has its workflow mirror (thin launcher counts)",
                not missing_ag, f"{len(missing_ag)} missing: {missing_ag[:6]}")

    if c.block("CS-03 · door CONTENT parity - a door that no longer says what its brain says"):
        # ── Door CONTENT parity (SCC-113 follow-on) ──────────────────────────────
        # Every check above asks whether a door EXISTS. None asks whether it still says what its
        # brain says, and that gap shipped a live break: SCC-77 landed the armed `main` write gate
        # on `main` without running /smh-sync-agents, so `.opencode/commands/` and
        # `.agents/workflows/` kept the pre-token merge steps while MAIN-PUSH-ENFORCE was armed.
        # An opencode or Antigravity agent following them reaches `git push origin main` with no
        # token and is refused, with nothing in its instructions telling it to mint one. Claude and
        # Codex were fine - their doors are thin launchers that read the brain live, which is
        # exactly why the drift was invisible to a human spot-check.
        #
        # SCC-77's close-out reported a fully green floor. This is the check that was missing.

        def door_verdict(brain: str, body: str, cmd_name: str, launcher_ok: bool) -> str:
            """'ok' | 'stale' | 'badlauncher' - for ONE mirror door against its command body.

        A mirror is one of exactly two legal things:
          * a FULL MIRROR, byte-identical to the brain; or
          * a THIN LAUNCHER - but ONLY on `.agents/workflows`, and only a current one.

        ⛔ `launcher_ok` is passed per-surface because **opencode has no launcher form.**
        `Sync-CommandDir` is `Copy-Item -Force` and nothing else; the launcher branch exists
        solely in `Sync-AntigravityWorkflowMirror`, for Antigravity's 12k cap. Offering the
        exemption to an opencode door let a 9 KB shipping command be replaced by a 9-line
        pointer with the suite green - an opencode agent invoking it would get a signpost
        instead of the gate-and-merge steps.
        """
            if body == brain:
                return "ok"
            # SCC-195: on `.agents/workflows` (launcher_ok, i.e. the Antigravity surface) the
            # legal full mirror is the brain with its description cut to the menu budget, and
            # NOTHING else changed. On opencode there is no budget and no launcher: byte
            # identity or it is stale.
            if launcher_ok and body == with_ag_description(brain):
                return "ok"
            # `launcher_ok` is true only on `.agents/workflows`, which is exactly the surface
            # the budget applies to - so it doubles as the budgeted flag here.
            if launcher_ok and is_launcher_for(body, brain, cmd_name, budgeted=True):
                return "ok"
            if GEN in body:
                return "badlauncher"   # claims to be generated, but is not a current launcher
            return "stale"

        # Controls first, as pure string cases - the live sweep below can only ever prove the
        # tree is currently clean, which is not the same as proving the check has teeth.
        BRAIN = "---\ndescription: Do the thing.\nplatforms: [antigravity]\n---\n# /x\n\nbody\n"
        LAUNCHER = ("---\ndescription: Do the thing.\n---\n"
                "# /x - launcher (GENERATED by sync-agents; do not edit)\n"
                "**Execute now:** read `.agents/commands/x.md` and follow it END TO END\n")
        WF, OC = True, False          # launcher form exists on workflows only

        c.check("door-parity CONTROL: an identical mirror is ok",
                door_verdict(BRAIN, BRAIN, "x.md", WF) == "ok")
        c.check("door-parity CONTROL: a STALE mirror is caught",
                door_verdict(BRAIN, BRAIN.replace("body", "old body"), "x.md", WF) == "stale",
                "this is the SCC-77 shape - a door that still reads the pre-change steps")
        c.check("door-parity CONTROL: a truncated mirror is caught",
                door_verdict(BRAIN, "---\ndescription: Do the thing.\n---\n# /x\n", "x.md", WF)
                == "stale")
        c.check("door-parity CONTROL: a current thin launcher is exempt",
                door_verdict(BRAIN, LAUNCHER, "x.md", WF) == "ok")

        # ⭐ The three shapes a clean-room pass used to defeat the FIRST cut of this exemption,
        # which tested three substrings appearing anywhere in the file.
        c.check("door-parity CONTROL: a launcher whose BRAIN's description moved on is caught",
                door_verdict(BRAIN.replace("Do the thing.", "RETIRED - use /y instead."),
                             LAUNCHER, "x.md", WF) == "badlauncher",
                "the forgotten-sync shape: nobody touched the launcher, and it is now lying to "
            "the Antigravity menu about what this command does")
        c.check("door-parity CONTROL: a launcher REPOINTED at another brain is caught, even "
            "with the old path still present in a comment",
                door_verdict(BRAIN,
                             "<!-- generated from .agents/commands/x.md -->\n"
                             + LAUNCHER.replace("read `.agents/commands/x.md`",
                                                "read `.agents/commands/other.md`"),
                             "x.md", WF) == "badlauncher",
                "a substring test reads the stale COMMENT as the pointer - the exact "
            "comment-literals-invert-source-grep-tests inversion")
        c.check("door-parity CONTROL: the marker alone does NOT excuse drift",
                door_verdict(BRAIN, "# GENERATED by sync-agents\nanything at all\n", "x.md", WF)
                == "badlauncher")

        # opencode has no launcher form at all - Copy-Item, or it is wrong.
        c.check("door-parity CONTROL: a launcher on an OPENCODE door is NOT exempt",
                door_verdict(BRAIN, LAUNCHER, "x.md", OC) == "badlauncher",
                "the engine never emits a launcher there; a pointer would replace the steps")

        # ⭐ REGRESSION CONTROL — the real historical defect, not a shape I imagined.
        # `ea8fe97` is the commit that re-synced the doors SCC-77 left stale; its parent holds the
        # genuinely stale `.opencode/commands/cicd-push-e2e.md` (8464b, zero mint-push-token
        # references) that the pre-SCC-113 gate passed 13/13. Every other control here is a string
        # I wrote, which only ever proves the check does what I expected it to.
        # Degrades LOUDLY, never silently: with no history reachable it synthesizes an equivalent
        # stale door and says so in the message, so the control always runs.
        hist = subprocess.run(["git", "show", "ea8fe97^:.opencode/commands/cicd-push-e2e.md"],
                              cwd=ROOT, capture_output=True, text=True)
        pushe2e = read(ROOT / ".agents/commands/cicd-push-e2e.md")
        if hist.returncode == 0 and hist.stdout.strip():
            stale_door, src = hist.stdout, "the REAL pre-ea8fe97 bytes"
        else:
            stale_door, src = pushe2e.split("## Step 6")[0], "a synthesized stale door (no history)"
        c.check(f"door-parity REGRESSION CONTROL fires on {src}",
                door_verdict(pushe2e, stale_door, "cicd-push-e2e.md", launcher_ok=False)
                == "stale",
                "the gate reported 13/13 green on exactly this file - that is the whole reason "
            "this check exists")

        MIRRORS = (".opencode/commands", ".agents/workflows")
        drifted, examined = [], 0
        for cmd in cmds:
            brain = read(cmd)
            for rel in MIRRORS:
                # A hand-owned workflow is authored, not generated, and legitimately differs from
                # its brain — `smh-adviser-board` is a condensed 2 KB Antigravity variant of a
                # 52 KB command. The engine never writes these, so parity is not the contract.
                if rel == ".agents/workflows" and cmd.name in hand_owned:
                    continue
                door = ROOT / rel / cmd.name
                if not door.is_file():
                    continue
                examined += 1
                v = door_verdict(brain, read(door), cmd.name,
                                 launcher_ok=(rel == ".agents/workflows"))
                if v != "ok":
                    drifted.append(f"{rel}/{cmd.name} [{v}]")

        c.check("every mirror door still says what its brain says",
                not drifted,
                f"{len(drifted)} drifted - run /smh-sync-agents: {drifted[:6]}")

        # ⭐ An empty sweep is indistinguishable from a clean one, and "0 offenders" out of 0 doors
        # is the vacuous green `tests-must-gate-for-real` names. A renamed cache directory or a
        # typo'd glob would otherwise read as a pass forever.
        c.check("door-parity examined a real number of doors (not a silent empty sweep)",
                examined >= 40, f"only {examined} mirror doors examined")

    if c.block("CS-04 · the generator is actually generating"):
        # ── Positive control: the generator must actually be generating ───────────
        # Without this, every check above passes trivially if the emit stage silently no-ops.
        generated = [d.name for d in master_skills.iterdir()
                     if (d / "SKILL.md").is_file() and GEN in read(d / "SKILL.md")]
        c.check("the launcher generator produced doors (not a silent no-op)",
                len(generated) >= 10, f"only {len(generated)} generated launchers")

    if c.block("CS-05 · hand-authored skills survive a sync untouched"):
        # ── Hand-authored skills are never overwritten by the generator ───────────
        # These carry real content (boundaries, routing notes) a stub would destroy.
        hand = ["cicd-park", "cicd-resume", "cicd-close-workingtree", "smh-close-task-merge-tree",
                "cicd-update-sprint-memory", "smh-update-maps-indexes"]
        clobbered = [n for n in hand
                     if (master_skills / n / "SKILL.md").is_file()
                     and GEN in read(master_skills / n / "SKILL.md")]
        c.check("hand-authored skills survive a sync untouched",
                not clobbered, f"overwritten by the generator: {clobbered}")

    if c.block("CS-06 · every skill door is loadable"):
        # ── Every skill door is loadable: frontmatter with a description ──────────
        no_fm = []
        for d in sorted(master_skills.iterdir()):
            sk = d / "SKILL.md"
            if not sk.is_file():
                continue
            head = read(sk)[:1200]
            if not head.startswith("---") or "description:" not in head:
                no_fm.append(d.name)
        c.check("every skill door carries frontmatter with a description",
                not no_fm, f"{len(no_fm)}: {no_fm[:6]}")

    if c.block("CS-07 · ghost doors - a mirror with no command source"):
        # ── Stale mirrors: a door with no command source is a ghost ───────────────
        cmd_names = {p.name for p in (ROOT / ".agents/commands").glob("*.md")}
        # ⛔ The ghost exemption is NOT `hand_owned`, and the difference is load-bearing. Only
        # `INDEX.md` is legitimately SOURCELESS; the other two hand-owned workflows are variants
        # OF a command and must keep having one. Exempting them here (as a first cut did, by
        # reusing `hand_owned`) made this check go silent on the one shape it most needs to
        # catch - a hand-authored launcher left pointing at a brain that was deleted. Verified:
        # delete `.agents/commands/smh-adviser-board.md` and the loose version reports 0 ghosts.
        wf_present = sorted(p.name for p in (ROOT / ".agents/workflows").glob("*.md"))
        ghosts = [n for n in wf_present if n not in cmd_names and n not in SOURCELESS]
        c.check("no ghost workflow mirrors (every one has a command source)",
                not ghosts, f"{len(ghosts)}: {ghosts[:6]}")
        orphaned_hand = sorted(n for n in hand_owned - SOURCELESS if n not in cmd_names)
        c.check("every hand-owned workflow still has the command it is a variant of",
                not orphaned_hand,
                f"{orphaned_hand} - excluded from the sync, so nothing else would notice")

        # ⭐ The SAME check for opencode, which never had one.
        #
        # ⛔ CORRECTED (SCC-113). This comment used to end "it falls to that final `$false` and is
        # kept FOREVER". That is FALSE, and it was false because I read `Sync-CommandDir` in
        # isolation and stopped one line short of its caller: `Invoke-ManifestPurge`
        # (sync-agents.ps1:822) runs immediately after and retires the door. The claim named a
        # danger that does not exist, in the comment explaining why the check is needed.
        #
        # The TRUE reason, which is narrower and still worth a check. `Sync-CommandDir` runs for
        # opencode WITHOUT `-Mirror` (sync-agents.ps1:821) and its purge branch ends
        # `else { $false }  # local: keep foreign/project-own files`, so the sweep itself never
        # removes a door whose brain was deleted. The manifest then covers exactly one case:
        # ⭐ `Invoke-ManifestPurge` (sync-agents.ps1:365) iterates `$was` - the names the LAST run
        # recorded writing - and removes only those the current run no longer owns (`:367`).
        # So a door the sync once wrote IS retired, and a door it never recorded - one predating
        # the manifest, hand-dropped, or authored by this repo - survives indefinitely with nothing
        # in the tree noticing. That residue is what this check covers, and it is precisely the case
        # `project-own.txt` exists to adjudicate: claimed means deliberate, unclaimed means stale.
        #
        # The keep-list is honoured HERE and only here (SCC-113). `Get-SurfaceState` maps
        # `.agents\workflows` to the MASTER's own workflows (sync-agents.ps1:325), so in this repo
        # that surface is compared against itself and can never produce an orphan — `-Reconcile`
        # cannot stage a lobby workflow into the keep-list, and this file is lobby-only
        # (ROOT = parents[3]). Wiring the exemption into the workflows sweep above would be
        # unreachable code dressed as symmetry.
        oc_present = sorted(p.name for p in (ROOT / ".opencode/commands").glob("*.md"))
        own_list = ROOT / ".agents/project-own.txt"
        # ABSENT is not the same as EMPTY, and the engine draws that line too: `Get-OwnAllowList`
        # returns `$null` for a missing file (which BLOCKS `-Reconcile` from purging anything) and
        # `@()` for an authored-but-empty one (which authorises purging every unclaimed orphan).
        # Here both read as "claim nothing", which is the strict side of that split in either case.
        own_claimed = frozenset(parse_own_list(read(own_list)) if own_list.is_file() else ())
        oc_ghosts = ghost_doors(oc_present, cmd_names, own_claimed)
        c.check("no ghost opencode mirrors (every one has a command source or a keep-list claim)",
                not oc_ghosts,
                f"{len(oc_ghosts)}: {oc_ghosts[:6]} - no command source, and the manifest cannot "
            f"retire what no previous sync recorded writing, so nothing else will ever say so. "
            f"If a door is deliberately this repo's own, claim it in .agents/project-own.txt "
            f"(sync-agents -Reconcile stages that file for you)")

        # Both sweeps get A-3's guard: "0 ghosts" out of 0 files read is the vacuous green, and a
        # renamed cache directory is exactly how you get one. Today: 34 workflows, 53 opencode.
        c.check("the ghost sweeps read a real number of doors (not two empty directories)",
                len(wf_present) >= 20 and len(oc_present) >= 40,
                f"workflows={len(wf_present)} opencode={len(oc_present)} - a glob resolved to "
            f"nothing, so every ghost check above passed on an empty set")

    if c.block("CS-08 · the engine's project-own keep-list"):
        # ── The engine's keep-list is part of the contract this sweep guards (SCC-113) ─────
        # `-Reconcile` STAGES `.agents/project-own.txt` (sync-agents.ps1:861) and
        # `smh-sync-agents.md:55` promises an orphan claimed there is "kept forever". A claimed
        # opencode door is therefore kept ON PURPOSE - calling it a ghost would indict the engine's
        # own documented resolution and leave the operator no way to close the finding.
        #
        # The rule is a PURE FUNCTION, and these controls pass it literals. `project-own.txt` does
        # not exist in this repo, so an exemption wired only to disk would be a permanent green
        # that never once ran the exempting path - the vacuous shape A-3 was raised about.
        c.check("own-list: a claimed door is not a ghost",
                ghost_doors(["a.md"], set(), frozenset({"a.md"})) == [],
                "the engine keeps a claimed door forever; the sweep must agree")
        c.check("own-list: an UNCLAIMED door is still a ghost",
                ghost_doors(["a.md"], set(), frozenset({"b.md"})) == ["a.md"],
                "NEGATIVE CONTROL - an exemption that swallows the check is worse than none")
        c.check("own-list: comments and blanks strip exactly as the engine strips them",
                parse_own_list("# header\n\n  a.md  \nb.md # why it is ours\n") == {"a.md", "b.md"},
                "a parser more generous than sync-agents.ps1:309 exempts doors it still purges")
        c.check("own-list: `*` is a literal name, never a wildcard",
                ghost_doors(["a.md", "b.md"], set(), parse_own_list("*\n")) == ["a.md", "b.md"],
                "a malformed keep-list must never widen the exemption to everything")
        c.check("own-list: a claim is an EXACT name, never a prefix",
                ghost_doors(["smh-sync-agents.md"], set(), parse_own_list("smh-sync\n"))
                == ["smh-sync-agents.md"],
                "prefix matching would let one claim cover every sibling door")
        c.check("own-list: a claim matches regardless of CASE, as the engine's -contains does",
                ghost_doors(["Smh-Review.md"], set(), parse_own_list("smh-review.md\n")) == [],
                "case-sensitive here + case-insensitive in PowerShell = the sweep calls a door a "
            "ghost that the engine keeps forever")

    if c.block("CS-09 · the docs agree with the engine"):
        # ── The docs agree with the engine ────────────────────────────────────────
        agents_md = read(ROOT / "AGENTS.md")
        c.check("root AGENTS.md documents the door model for every platform",
                "one door per platform per command" in agents_md.lower()
                and "launcher skill" in agents_md,
                "AGENTS.md no longer documents the door model")
        sync_cmd = read(ROOT / ".agents/commands/smh-sync-agents.md")
        c.check("sync-agents command doc names both retired doors",
                "RETIRED door" in sync_cmd and "/prompts:<name>" in sync_cmd
                and "Do not use `-Maintained`" in sync_cmd,
                "smh-sync-agents.md no longer matches what the engine does")

    if c.block("CS-10 · mutation doctrine: named, loaded into the task lane, and pinned"):
        # ── Mutation doctrine: named, loaded into the task lane, and pinned (SCC-145) ─────
        # Mutation testing was a doctrine nobody was handed, nothing named, and no gate could see:
        # `grep -rn "mutant\|mutation" .agents/commands/` returned two hits, one of them a biologist
        # in the adviser board. The whole procedure was ONE sub-bullet under Rule 4 of
        # `tests-must-gate-for-real.md`, and the two TASK-lane commands that write the assertions
        # (`/smh-quick-dev`, `/smh-self-audit`) did not load that rule at all — so on a task lane the
        # doctrine arrived at REVIEW, one step after the mutants were designed.
        #
        # It was measured twice, in unrelated lanes, as the same wasted work: SCC-144 aimed a mutant
        # at the wrong gate's stdin and paid a second run; its 13-mutant sweep left a survivor that
        # turned out to be a DEFECTIVE mutant (it commented out one echo of a two-line message, so the
        # asserted word still printed); a `timeout`-killed sweep left a MUTATED GATE on disk,
        # uncommitted, in the very lane whose job was fixing that gate; and its review found its 14
        # case-derived mutants all killed while a later set drawn from the CODE left 24 of 25 surviving.
        # SCC-129 hit the same class inside a test file — a "proven able to fail" row that gutted its
        # own input, empty by construction.
        #
        # Nothing here can be pinned by wiring, because the artifact IS prose. So the check pins the
        # two things prose can still get structurally wrong: WHERE the obligation sits (the block an
        # agent reads as law; the step that routes the mutating) and WHETHER each technique is present
        # by name. Both helpers above fail closed on an empty search space.
        RULE_STEM = "tests-must-gate-for-real"

        # The TASK-lane commands that write or judge assertions. Story-lane commands
        # (`cicd-dev-story-tests`, `cicd-write-story-tests`, `cicd-code-review`, both clean-code
        # audits) bake the rule into the STEP BODIES that route the work instead — the stronger form
        # per `restate-alwayson-obligations-in-command-bodies` — and two of them carry no
        # rules-in-force block at all. Widening those five is a change to five contracts and two `-AP`
        # twins; it is deliberately not this ticket. `smh-code-review` is listed because it already
        # complies, and an unpinned compliance is one edit from being gone.
        LOADERS = ("smh-quick-dev.md", "smh-self-audit.md", "smh-code-review.md")
        unloaded = [n for n in LOADERS
                    if RULE_STEM not in rif_block(read(ROOT / ".agents/commands" / n))]
        c.check("the mutation rule is LOADED (in the rules-in-force block) by every task-lane "
            "command that writes or judges assertions",
                not unloaded,
                f"{unloaded} - cite `.agents/rules/{RULE_STEM}.md` INSIDE the block, not in step "
            f"prose. The block is what an agent reads as standing law before Step 0; SCC-144 "
            f"designed 14 mutants on a lane where this rule was never loaded")

        # Controls — pure strings, no disk. The sweep above can only prove the tree is clean today.
        RIF = ("> **Rules in force for this command:**\n"
           "> - `.agents/rules/git-policy.md` — explicit paths only\n")
        c.check("rules-in-force CONTROL: a rule cited INSIDE the block is loaded",
                RULE_STEM in rif_block(RIF + f"> - `.agents/rules/{RULE_STEM}.md` — the why\n"))
        c.check("rules-in-force CONTROL: a rule cited only in BODY PROSE is NOT loaded",
                RULE_STEM not in rif_block(
                    RIF + f"\n## Step 3\n\nrun one sweep per `{RULE_STEM}`\n"),
                "a file-wide grep reads this as loaded - it is the shape five commands are actually "
            "in, and it arrives after the decision it governs")
        c.check("rules-in-force CONTROL: no block at all fails CLOSED",
                rif_block("# /x\n\nprose only, no block here\n") == "",
                "an empty search space must never read as a pass")
        # ⛔ THE ONE THAT PINS `break` RATHER THAN `continue`. The control above uses plain prose, which
        # a degenerate `rif_block` collecting EVERY blockquote in the file would also pass. These
        # commands are full of later `> **Note:**` asides (`smh-quick-dev.md` has two within 20 lines
        # of the block), so "any blockquote anywhere" is not a theoretical degeneration - it is what
        # the file actually looks like. Mutating `break` to `continue` left all four call sites green.
        c.check("rules-in-force CONTROL: a LATER blockquote is not part of the block",
                RULE_STEM not in rif_block(
                    RIF + f"\ntext between\n\n> **Note:** we follow `{RULE_STEM}.md` here\n"),
                "the block ENDS at the first non-`>` line; a rule named in a later aside is not "
            "loaded law, and a helper that swept every blockquote would call it one")

        # ⭐ The obligation must sit in the step that routes the mutating. Step 3 is GREEN (where the
        # mutants get run); Step 3.5 is the eject tripwire and Step 2 is RED - a bullet that drifts
        # into either fires at the wrong moment, and file-wide pinning cannot see the difference.
        STEP3_RX = r"^## Step 3(?![\d.])"
        step3 = md_section(read(ROOT / ".agents/commands/smh-quick-dev.md"), STEP3_RX)

        # Each row is ONE obligation and the phrasings that satisfy it - **alternatives, never a single
        # literal**. The rule and the SOP name the technique `CODE-DERIVED` where the command says
        # "from the code", so a meaning-preserving edit that HARMONISES the three surfaces (exactly what
        # a findability ticket invites) would have gone RED against one pinned string. A guard that
        # punishes the edit it exists to encourage is a false red, and this repo has shipped four gates
        # that hard-blocked a close-out on one. Everything is compared case-folded, on both sides,
        # because the capitalisation of a word in prose is not the contract - its presence is.
        STEP3_OBLIGATIONS = (
            ("declare the table", ("mutant table",)),
            ("ONE sweep", ("one sweep",)),
            ("a survivor is a finding", ("surviving", "survivor")),
            ("DEFECTIVE mutants get re-aimed", ("defective",)),
            ("drawn from the CODE", ("from the code", "code-derived")),
            ("restore, and verify it restored", ("git status",)),
        )
        missing_terms = [n for n, alts in STEP3_OBLIGATIONS
                         if not any(a in step3.lower() for a in alts)]
        c.check("/smh-quick-dev Step 3 carries the mutant-table obligation, in the step that "
            "actually routes the mutating",
                step3 != "" and not missing_terms,
                f"missing from `## Step 3`: {missing_terms}" if step3 else
                "`## Step 3` not found at all - the section heading moved and the obligation is "
            "now anchored to nothing")

        c.check("section CONTROL: a named section is found and bounded at the next heading",
                md_section("## A\nx\n## B\ny\n", r"^## A$") == "## A\nx")
        c.check("section CONTROL: `## Step 3` does not swallow `## Step 3.5`",
                "3.5" not in md_section("## Step 3 — GREEN\na\n## Step 3.5 — EJECT\nb\n", STEP3_RX),
                "the eject tripwire is a different step; an obligation drifting into it must go red")
        # ⛔ THE CONTROL ABOVE CANNOT FAIL ON ITS OWN, and that is why this one exists. Its input
        # carries BOTH headings in file order, so `md_section` takes `## Step 3` on first-match with or
        # without the `(?![\d.])` lookahead - deleting the lookahead left all 52 cases green. The input
        # the lookahead actually guards is the one where `## Step 3` is ABSENT and the obligation has
        # drifted into the eject step: without it, `## Step 3.5` matches and the drift reads as
        # compliance. A control that passes against both the guard and its mutant is decoration.
        c.check("section CONTROL: with `## Step 3` ABSENT, `## Step 3.5` must not stand in for it",
                md_section("## Step 3.5 — EJECT\nmutant table one sweep defective\n", STEP3_RX) == "",
                "this is the input that kills the `(?![\\d.])` lookahead; the paired control above "
            "passes with or without it")
        c.check("section CONTROL: the practice named only in BODY PROSE is not a section",
                md_section("## Why\n\nthe first mutation check deleted the guard\n",
                           r"^##\s+.*mutation") == "",
                "the rule has carried the word 'mutation' in its `## Why` narrative since it was "
            "written, while the practice itself was an unnamed sub-bullet - a body search would "
            "have called the doctrine documented all along")

        # ⭐ The rule must NAME the practice in a heading, and carry every technique. One technique is
        # what it used to have, and it was the wrong one for a gate: RELOCATE assumes a structural
        # guard and a behavioral test in one file, and a shell gate has nothing to relocate.
        #
        # ⛔ ANCHORED TO EACH BULLET'S OWN LEAD, never to the bare word. Pinning `"RELOCATE"` alone was
        # a FALSE GREEN: the whole RELOCATE bullet could be deleted and the token still survived one
        # bullet down, inside INVERT's prose ("the shape RELOCATE does not transfer to") - so the guard
        # held for the four techniques that happened to be unique and let go of the single one the
        # section exists to correct.
        mutation_sec = md_section(read(ROOT / f".agents/rules/{RULE_STEM}.md"),
                                  r"^##\s+.*mutation").lower()
        TECHNIQUES = (
            ("RELOCATE", ("relocate the guard",)),
            ("INVERT", ("invert the decision",)),
            ("DEFECTIVE", ("defective",)),
            ("CODE-DERIVED", ("code-derived",)),
            ("RESTORE", ("restore on interrupt", "restore in a")),
        )
        absent = [n for n, alts in TECHNIQUES if not any(a in mutation_sec for a in alts)]
        c.check("the mutation rule has a section whose HEADING names the practice, carrying every "
            "technique",
                mutation_sec != "" and not absent,
                f"techniques missing from the section: {absent}" if mutation_sec else
                f"no `##` heading in {RULE_STEM}.md names mutation - the doctrine is unfindable by "
            f"anyone grepping for how to do it, which is the whole finding")

        # ⭐ The SOP page is the THIRD surface this ticket writes to, and it was the one nobody gated:
        # the entire `### Mutation` section and its mermaid node could be deleted with the suite green.
        # `sop_currency.py` only forces the SOP to be STAGED in the same commit - never to still say
        # anything - so without this the operator's own reference is the surface that silently rots.
        sop_txt = read(ROOT / "docs/_scc_sops_prds/workflows_testing_SOP.md").lower()
        sop_named = any(ln.startswith("#") and "mutation" in ln for ln in sop_txt.splitlines())
        sop_missing = [n for n, alts in STEP3_OBLIGATIONS
                       if not any(a in sop_txt for a in alts)]
        c.check("the SOP page names the practice in a heading and carries the same obligation",
                sop_named and not sop_missing,
                f"SOP heading names mutation: {sop_named}; obligations missing: {sop_missing} - the "
            f"operator's own reference had ZERO mentions of the practice before SCC-145")

        # ⛔ THE SCOPE OF THIS SECTION IS ITSELF PINNED - and it is not optional, because this file
        # already carries two "read a real number of X" guards for exactly this reason: an empty sweep
        # is indistinguishable from a clean one. `LOADERS`, `MUTANT_TERMS` and `TECHNIQUES` ARE the
        # scope of every case above, and an unpinned scope is one edit away from checking nothing.
        #
        # PROVEN, not supposed. Three CODE-DERIVED mutants on the constants above each left the suite
        # 52/52 GREEN before these two cases existed:
        #     LOADERS   -> ("smh-code-review.md",)   ← drops BOTH commands this section exists to
        #                                              protect, and every case still passed
        #     MUTANT_TERMS -> ()                     ← the Step 3 obligation unpinned
        #     TECHNIQUES   -> ()                     ← all five techniques unpinned
        # That is SCC-145's own new CODE-DERIVED rule catching SCC-145: of its eight declared mutants
        # only two were drawn from this guard's source, and both hit the HELPERS, never the constants.
        # Restating a literal is normally circular; here it is what converts a silently mutable knob
        # into a decision that has to be argued for in a diff - the same reason `hand` and `SOURCELESS`
        # above are spelled out rather than derived.
        c.check("the LOADERS sweep still covers BOTH task-lane commands (its scope cannot be "
            "narrowed silently)",
                {"smh-quick-dev.md", "smh-self-audit.md"} <= set(LOADERS),
                f"LOADERS={LOADERS} - `/smh-quick-dev` WRITES the assertions and `/smh-self-audit` "
            f"judges the plan that picks them. Dropping either restores the exact gap this "
            f"section exists to close, with every other case here still green")
        obligations = {n for n, _ in STEP3_OBLIGATIONS}
        techniques = {n for n, _ in TECHNIQUES}
        c.check("the obligation and technique lists still name what they are supposed to pin",
                {"ONE sweep", "DEFECTIVE mutants get re-aimed", "drawn from the CODE"} <= obligations
                and {"RELOCATE", "INVERT", "CODE-DERIVED", "RESTORE"} <= techniques,
                f"obligations={sorted(obligations)} techniques={sorted(techniques)} - an emptied list "
            f"makes its own sweep pass against anything, including a rule with the section gone")

    # ── CS-11: the review twins - blast radius, acceptance audit, and each lane's own ref ─────
    if c.block("CS-11 · the review twins: blast radius, acceptance audit, and each lane's "
               "own integration ref"):
        # `/smh-code-review` and `/cicd-code-review` do the same job on two lane shapes, and two
        # steps existed on the Task side ONLY: the post-dev blast-radius re-derivation (sibling
        # lanes land while you build, so the pre-work audit expires) and the acceptance audit
        # against the checkable list. A story lane carries both hazards - sibling STORIES land on
        # the epic branch mid-story - so the absence was a gap, not a difference. Everything the
        # comparison found that IS a difference is recorded in the ticket and deliberately left.
        #
        # ⛔ ADAPTED, NEVER COPIED, and that is what most of these cases are for. smh re-derives
        # against `origin/main` because a Task lane merges to main; a story lane merges to its
        # EPIC branch. Copying smh's step verbatim would plant the exact stale-ref defect
        # SCC-165 removes, three lines under the guard that removes it.
        review = {n: read(ROOT / ".agents/commands" / n)
                  for n in ("smh-code-review.md", "cicd-code-review.md")}
        blast = {n: md_section(t, r"^##\s.*blast radius") for n, t in review.items()}
        accept = {n: md_section(t, r"^##\s.*acceptance audit") for n, t in review.items()}
        step0 = {n: md_section(t, r"^## Step 0 ") for n, t in review.items()}

        # STRUCTURE, not wording. Every item is a command the step RUNS or a shape it must
        # produce: `merge-base` to find where the lanes parted, `merge-tree` to surface the
        # conflict before it is real, `worktree list` for the siblings still live, and three
        # numbered answers that have to be written down. A wording pin is satisfied by a
        # paraphrase that runs nothing - `prose-pinning-guards-are-vacuous`, in the guard.
        def blast_gaps(body: str) -> list[str]:
            gaps = [w for w in ("merge-base", "merge-tree", "worktree list") if w not in body]
            gaps += [f"answer {i}" for i in (1, 2, 3)
                     if not re.search(rf"^\s*{i}\.\s", body, re.M)]
            return gaps

        for n in review:
            c.check(f"{n} carries the blast-radius re-derivation, with all three answers",
                    bool(blast[n]) and not blast_gaps(blast[n]),
                    "no such section" if not blast[n]
                    else f"missing: {blast_gaps(blast[n])}")

        # ⭐ THE ADAPTATION, made mechanical. Each twin's section must name the ref ITS lane
        # actually merges into, and must not name the other's. `origin/main` in the story
        # command's step is not a nit: an agent re-derives against a branch its work will never
        # meet, reports "nothing moved", and the epic-mate that DID move the file lands anyway.
        c.check("smh's blast radius re-derives against origin/main (a Task lane merges to main)",
                "origin/main" in blast["smh-code-review.md"],
                "the Task lane's integration ref is main; it is not the story lane's")
        # A PURE FUNCTION, called by the live check AND by its controls below. A control that
        # restates the rule as its own literal proves the literal, not the rule: drop the
        # `origin/main` arm here and a restated control stays green while the guard goes blind.
        def story_ref_ok(body: str) -> bool:
            return "origin/$EPIC" in body and "origin/main" not in body

        c.check("⭐ cicd's blast radius re-derives against the EPIC branch, and never origin/main",
                story_ref_ok(blast["cicd-code-review.md"]),
                "a story lane merges to `epic/<KEY>-<slug>`. Naming origin/main here re-derives "
                "against a branch this work never meets - SCC-165's defect, re-planted")

        # The acceptance audit is an EVIDENCE contract, so the two clauses that make it one are
        # what get pinned: no evidence is not satisfied (and caps the verdict), and the reverse
        # direction - anything in the diff past the list is drift.
        for n in review:
            body = accept[n]
            c.check(f"{n} carries the acceptance audit, with its floor and the drift direction",
                    bool(body) and "CONCERNS" in body and "drift" in body.lower(),
                    "no such section" if not body else "section present, but an item with no "
                    "evidence does not cap the verdict, or nothing names diff-beyond-the-list "
                    "as drift - both halves are the audit")

        # Step 0 is where a review picks the WRONG TREE, and the fix is the same on both lanes:
        # echo what the commands returned. `preflight-resolves-repo-from-cwd` is the live
        # incident - a preflight reported another lane's branch as clear to merge.
        for n in review:
            c.check(f"{n} Step 0 resolves its target from command output, never from belief",
                    "rev-parse" in step0[n] and "never from belief" in step0[n].lower(),
                    f"Step 0 {'is missing' if not step0[n] else 'does not echo rev-parse output'}")

        # B3, SCOPED (plan rev 2, F7): the per-file sweep covers the files THIS part edits. The
        # toolkit-wide count is recorded in the walkthrough and is a separate, confirm-scope task
        # (`no-personal-name-in-directives`) - `rules/operator-profile.md` is a file where the
        # name IS the subject, so a blanket sweep needs an allowlist and its own ruling.
        #
        # ⛔ The name is BUILT from halves, never written. This file lives under `.agents/`; a
        # guard that spells the operator's name out breaks the rule it enforces, in the file
        # claiming to enforce it.
        NAME = "Dan" + "iel"

        def name_hits(text: str) -> list[int]:
            return [i for i, ln in enumerate(text.splitlines(), 1) if NAME in ln]

        for n in ("cicd-code-review.md", "cicd-push-e2e.md"):
            hits = name_hits(read(ROOT / ".agents/commands" / n))
            c.check(f"{n} names a generic referent, not a person", not hits,
                    f"{len(hits)} line(s): {hits} - a directive addressed to one named human "
                    f"reads as inapplicable to every other reader, including the agent")

        # Controls. Each of the four rules above is clean on today's tree, and a clean sweep
        # says nothing about whether the rule has teeth - these are the mutants, run as data.
        GOOD_BLAST = ("## Step 0.7 - blast radius\n```bash\nmerge-base\nmerge-tree\n"
                      "worktree list\n```\n1. moved?\n2. overlap?\n3. siblings?\n")
        c.check("CONTROL: a complete blast-radius section passes",
                not blast_gaps(GOOD_BLAST))
        c.check("CONTROL: a blast-radius section that never probes for conflicts is caught",
                blast_gaps(GOOD_BLAST.replace("merge-tree\n", "")) == ["merge-tree"],
                "the step reads correctly and surfaces no conflict until the merge is real")
        c.check("CONTROL: a blast-radius section with only two answers is caught",
                blast_gaps(GOOD_BLAST.replace("3. siblings?", "and siblings")) == ["answer 3"],
                "landing order is the answer a green suite can never give you")
        EPIC_BLAST = GOOD_BLAST + '\nmerge-base HEAD "origin/$EPIC"\n'
        c.check("CONTROL: a story-lane section naming the epic ref passes",
                story_ref_ok(EPIC_BLAST))
        c.check("CONTROL: origin/main planted in a story-lane section is caught",
                not story_ref_ok(EPIC_BLAST + "git merge-base HEAD origin/main\n"),
                "NEGATIVE CONTROL - the trunk substituted for the epic branch is the whole "
                "defect this step was adapted to avoid; the rule must fire on it")
        c.check("CONTROL: a story-lane section naming NEITHER ref is caught",
                not story_ref_ok(GOOD_BLAST),
                "NEGATIVE CONTROL - a section that re-derives against nothing must not pass "
                "merely by omitting the wrong ref")
        c.check("CONTROL: the personal-name rule fires on a planted name, at its line",
                name_hits(f"first line\nInvoking this IS {NAME}'s sign-off\n") == [2],
                "NEGATIVE CONTROL - a sweep that cannot see the name it searches for is a "
                "permanent green")
        c.check("CONTROL: the personal-name rule does not fire on a clean file",
                name_hits("Invoking this command IS the operator's sign-off\n") == [],
                "NEGATIVE CONTROL - a rule that fires on everything is not a rule")

    # ── CS-12: the port checklist - the rule, its trigger, and the row that makes it stick ───
    if c.block("CS-12 · the port checklist: the rule carries six answerable checks, the "
               "plan/audit commands trigger on it, and the lint row makes the citation "
               "mechanical"):
        # Every lobby<->project port so far (AVCH-54, AVCH-59) cost an afternoon and found the
        # SAME class of defect: the centre's copy is subtly wrong once it runs in a SUBMODULE, on
        # WINDOWS, in a WORKTREE, in a THIN repo. Nothing asked those questions at PLAN time, so
        # they surfaced at review or on the other machine. H answers that with a rule plus prose
        # in three commands - an agent executes both, and neither is machine-checkable. What IS
        # machine-checkable is pinned here: the rule's SHAPE (six items, each ANSWERED BY A
        # COMMAND rather than a reminder) and the `_RULE_POINTERS` row's WIRING, exercised by
        # calling the real `check_rule_pointers` over fixture trees.
        def safe(rel: str) -> str:
            p = ROOT / rel
            return read(p) if p.exists() else ""

        checklist = safe(".agents/rules/port-checklist.md")
        rules_idx = safe(".agents/rules/INDEX.md")
        PORT_CMDS = ("smh-plan-task.md", "smh-self-audit.md", "cicd-self-audit.md")
        # The phrase step (2) writes into all three, and the command that answers "do the two
        # copies differ?". Both are the ROW's key - see the row's own comment for why the
        # concept-keyed sketch ("port" as a step verb) was thrown out.
        TRIGGER = "exists in more than one repo"
        CITE = ".agents/rules/port-checklist.md"

        def checklist_items(body: str) -> list[tuple[str, str]]:
            """The `### ` items, each bounded by the next - title and its own text."""
            parts = re.split(r"^###\s+", body, flags=re.M)[1:]
            return [(s.splitlines()[0].strip(), s) for s in parts]

        def unanswered(body: str) -> list[str]:
            """Items with no fenced command block - a REMINDER, which H1 forbids."""
            return [title for title, text in checklist_items(body) if "```" not in text]

        def preamble(body: str) -> str:
            """Everything above the first item - WITHOUT the frontmatter.

            The `description:` restates the whole rule, "both directions" included, so a preamble
            that kept it would stay green with the header sentence deleted: a mutant aimed at the
            body would survive on the strength of the metadata. Frontmatter is the router's copy,
            never the reader's.
            """
            body = re.sub(r"\A---\n.*?\n---\n", "", body, count=1, flags=re.S)
            return re.split(r"^###\s+", body, flags=re.M)[0]

        def pointer_warns(cmd_body: str) -> list[str]:
            """Run the REAL `check_rule_pointers` over a one-command fixture tree.

            Not a re-implementation of the row's regex: the fixture goes through the same
            function `workflow_lint --toolkit-only` calls, so deleting the row from the table
            takes these controls down with it. A control that restated the pattern would keep
            passing with the row gone - the exact vacuity this lane keeps finding.
            """
            with TempDir() as t:
                d = t / ".agents" / "commands"
                d.mkdir(parents=True)
                (d / "fixture-port.md").write_text(cmd_body, encoding="utf-8")
                rep = wf.Report()
                lint.check_rule_pointers(t, rep)
                return [i["msg"] for i in rep.items if i["sev"] == "WARN"]

        items = checklist_items(checklist)
        c.check("the port checklist exists and carries its six checks",
                len(items) == 6,
                f"got {len(items)} `### ` items in .agents/rules/port-checklist.md - the six "
                f"AVCH-59 divergence classes, no more and no fewer")
        c.check("every checklist item is ANSWERED BY A COMMAND, not phrased as a reminder",
                checklist and unanswered(checklist) == [],
                f"items with no fenced command: {unanswered(checklist)} - H1 requires each item "
                f"be a CHECK with the command that answers it; a reminder is what already failed")
        c.check("items 4 and 6 CITE project-law.md instead of restating the thin-repo law",
                sum(1 for _, text in items if "project-law.md" in text) >= 2,
                "the thin-repo and repo-local-enforcement items already live in "
                "`project-law.md`; a second copy is the drift this rule set exists to avoid")
        c.check("the header says the checklist runs in BOTH directions (H5)",
                "both directions" in preamble(checklist).lower(),
                "the AVCH-59 -> lobby port is a port too; a checklist that reads one-way is "
                "skipped on exactly the half this ticket is")
        c.check("the rules INDEX routes to the checklist",
                "port-checklist.md" in rules_idx,
                "a rule with no INDEX row is unreachable by the router every session scans")

        for name in PORT_CMDS:
            body = safe(f".agents/commands/{name}")
            c.check(f"{name} carries the port trigger and cites the checklist",
                    TRIGGER in body and CITE in body,
                    f"trigger={TRIGGER in body} cite={CITE in body} - the trigger without the "
                    f"citation is what the lint row is keyed to catch")

        planted = f"Step 9 - when the file {TRIGGER}, stop and diff the copies.\n"
        c.check("WIRING: the live row fires on a porting command that cites nothing",
                any("port-checklist" in m for m in pointer_warns(planted)),
                f"check_rule_pointers said {pointer_warns(planted)} - with no row in "
                f"`_RULE_POINTERS` a command can describe a port and point at nothing")
        c.check("WIRING: the second arm - a command that diffs the two copies also fires",
                any("port-checklist" in m
                    for m in pointer_warns("Run `git diff --no-index` over both copies.\n")),
                "the row keys on the trigger PHRASE and on the command that answers it; one arm "
                "alone goes blind the moment a command words the trigger differently")
        c.check("CONTROL: the same command WITH the citation is silent",
                pointer_warns(planted + f"See `{CITE}`.\n") == [],
                "NEGATIVE CONTROL - a row that warns even after the citation lands can never "
                "reach the tip's 0/0, so it would be disarmed rather than satisfied")
        c.check("CONTROL: a command that says nothing about porting is silent",
                pointer_warns("Step 1 - read the ticket. Step 2 - write the plan.\n") == [],
                "NEGATIVE CONTROL - the sketched `\\bport\\b` key matched seven unrelated "
                "command bodies (audit F26); a row that fires on everything is not a row")

        # ── The OTHER row in the same table: `work-consolidation` (Part 1) ────────────────
        # It shipped with no coverage at all, and its third arm was keyed on `landing:` - a
        # key `task_preflight` deliberately renamed to `landing_mode` - so it could never
        # match anything. A dead arm inside a live row is a check that cannot fail.
        c.check("WIRING: the work-consolidation row fires on a `riders:` body that cites nothing",
                any("work-consolidation" in m for m in pointer_warns("Set `riders: [SCC-1]`.\n")),
                f"check_rule_pointers said {pointer_warns('Set `riders: [SCC-1]`.')}")
        c.check("WIRING: ...and on `landing_mode: partial`, the arm that was DEAD",
                any("work-consolidation" in m
                    for m in pointer_warns("Declare `landing_mode: partial` in task.yaml.\n")),
                "the arm read `landing\\s*:\\s*partial`, which cannot match `landing_mode:` - "
                "so a body documenting the partial landing without the literal `riders:` "
                "escaped the pointer requirement entirely")
        c.check("CONTROL: the retired `landing:` spelling is NOT the machinery and stays silent",
                pointer_warns("Declare `landing: partial` in task.yaml.\n") == [],
                "NEGATIVE CONTROL - `landing:` is a DIFFERENT live key (nested under "
                "`secondary_repos:`); keying on it is what made the arm dead")
        c.check("CONTROL: the same consolidation body WITH the citation is silent",
                pointer_warns("Set `riders: [SCC-1]`. See `.agents/rules/work-consolidation.md`.\n")
                == [],
                "NEGATIVE CONTROL - a row that warns after the citation lands can never reach 0/0")

        live = wf.Report()
        lint.check_rule_pointers(ROOT, live)
        c.check("the live toolkit has no un-cited porting command",
                [i for i in live.items if "port-checklist" in i["msg"]] == [],
                f"{[i['msg'] for i in live.items if 'port-checklist' in i['msg']]}")


    # ══ SCC-191 · RULE 1 HAS FOUR RUNGS, AND THE THIRD IS THE ROLLING TICKET ═══════════════
    #
    # OPERATOR RULING, 2026-08-16, VERBATIM: "we should always have a New findings Ticket Open
    # to put things like this in. that way its one ticket that grows with sub task, we can add
    # this to the same rule about looking for an open ticket, if there is not a good one make a
    # 'Bugs and Updates Ticket' and add them as sub task to it. once it get big enough we run
    # it. or split it up into new tickets. close them all and create a new one thats the cycle"
    #
    # WHAT WAS WRONG: Rule 1's rung 3 was "nothing fits -> MINT", and it fired on MOST findings
    # that surface during a landing, because most have no thematic parent open. One new Task per
    # close-out, each costing a plan, a review and a ceremony, and a board of singletons.
    #
    # ⛔ WHY THIS IS PINNED AT ALL, given it is filing law and not a gate: the rule's SEARCH is
    # the enforcement ("say in ONE line what you looked at"), and a search that cannot surface
    # the rolling ticket lets an agent say "nothing fits" while one is open. The pin is
    # mechanical and narrow - the rungs exist, in order, and the search names the label - which
    # is all a machine can honestly check about a judgment rule.
    if c.block("SCC-191 · Rule 1's four rungs and the rolling ticket"):
        rule = read(ROOT / ".agents/rules/work-consolidation.md")
        body = rule.split("## Rule 2")[0]
        rungs = re.findall(r"^\s{0,3}(\d)\.\s+\*\*(.+?)\*\*", body, re.M)
        c.check("R1a Rule 1 has FOUR rungs", len(rungs) == 4,
                f"{len(rungs)}: {[r[1][:40] for r in rungs]}")
        c.check("R1b ...numbered 1-4 in order", [r[0] for r in rungs] == ["1", "2", "3", "4"],
                str([r[0] for r in rungs]))
        if len(rungs) == 4:
            third, fourth = rungs[2][1].lower(), rungs[3][1].lower()
            c.check("R1c rung 3 is the OPEN ROLLING TICKET", "rolling" in third, rungs[2][1][:80])
            c.check("R1d rung 4 is the mint, and it is now the last resort",
                    "mint" in fourth, rungs[3][1][:80])
        # ⭐ THE HEADING, not the word. `"cycle" in body` was satisfied by the operator's
        # quoted ruling ("thats the cycle"), so retitling the section to "Rung 3 notes" - which
        # is exactly how a cycle quietly becomes a footnote - left the check green (R-M3).
        cyc = re.search(r"(?m)^###\s+.*\bCYCLE\b.*$", body)
        c.check("R1e the cycle has its OWN heading, so it cannot decay into a footnote",
                bool(cyc), "no `### ... CYCLE ...` heading under Rule 1")
        c.check("R1e ...and it states run-or-split, close them all, open the next",
                all(w in body.lower() for w in
                    ("run", "split", "close", "next", "exactly one")),
                "the rule must name the cycle, not a threshold")
        # ⭐ SCOPED TO THE SEARCH BLOCK, and that is what R-M2 proved. `"bugs-and-updates" in
        # body` was satisfied by rung 3's PROSE, so deleting the jql line - the executable half,
        # the thing an agent actually runs - changed nothing the check could see. The rule's
        # enforcement IS the search; a label named only in prose is a label nobody queries.
        fences = re.findall(r"```(?:bash)?\n(.*?)```", body, re.S)
        searches = "\n".join(f for f in fences if "acli jira workitem search" in f)
        c.check("R2 the look-before-mint SEARCH BLOCK queries the rolling ticket's label",
                "labels = bugs-and-updates" in searches,
                "an agent must be able to FIND the open one from a command, or 'nothing fits' "
                f"is unfalsifiable. Search block: {searches[:160]!r}")
        c.check("R3 the live instance is named, so nobody mints a second one",
                "SCC-190" in body, "the rolling ticket that exists today")
        c.check("R4 the worked example (SCC-192, re-filed from a fresh Task) is recorded",
                "SCC-192" in body, "the re-filing IS the rule")

        # The rule is restated in four places. A stale restatement is a second source of law,
        # and this system has already paid for that once (the retired scrum board).
        for rel in (".agents/skills/code-review-engine/steps/step-01-review.md",
                    ".agents/commands/smh-quick-dev.md",
                    ".agents/commands/smh-quick-fix.md"):
            body_ = read(ROOT / rel).lower()
            if "rule 1" not in body_ and "work-consolidation" not in body_:
                continue
            c.check(f"R2b the restatement in {rel.split('/')[-1]} names the rolling ticket",
                    "rolling" in body_, "a stale restatement is a second source of law")


    # ══ SCC-195 · every Antigravity door fits the menu's budget ════════════════════════════
    if c.block("SCC-195 · the Antigravity description budget"):
        LONG = ("The TASK lane's dev cycle - assert-first development for command-centre work "
                "that has no story, no sprint board and no epic branch. Write the check that "
                "fails FIRST, then make it pass, then the review gate.")
        SHORT = "Close out TASK work."
        c.check("U1 a short description is returned unchanged (idempotent)",
                ag_description(SHORT) == SHORT, ag_description(SHORT))
        cut = ag_description(LONG)
        c.check("U2 a long one is cut to the budget and marked", len(cut) <= AG_DESC_MAX
                and cut.endswith("..."), f"{len(cut)}: {cut}")
        # ⭐ THE ASSERTION U-M3 PROVED WAS VACUOUS. This read `cut[:-3] in LONG`, and a HARD
        # cut at 132 is still a prefix of the original - so "ignore the word boundary" passed
        # it unchanged. The property is not "the text came from LONG", it is "the character
        # immediately after the kept text is a space", i.e. no word was split.
        kept = cut[:-3]
        c.check("U3 ...on a word boundary, never mid-word",
                LONG.startswith(kept) and LONG[len(kept):len(kept) + 1] == " ",
                f"kept={kept[-25:]!r} next={LONG[len(kept):len(kept) + 1]!r}")
        # ⛔ U3b · AND A STRING THE HARD CUT ACTUALLY SPLITS. `LONG` above is a lucky one:
        # its 132nd character lands just after a full stop, so `rstrip` leaves a clean word
        # boundary even with the boundary search DELETED - the mutant survived twice against
        # a case written to catch it. This string puts a long word ACROSS the cut, so only a
        # real backward search can end cleanly. (25x "word " = 125 chars, then a 27-letter
        # word, so index 132 is seven letters into it.)
        SPLIT = ("word " * 25) + "antidisestablishmentarianism is the tail"
        kept2 = ag_description(SPLIT)[:-3]
        c.check("U3b ...even when a long word straddles the cut point",
                SPLIT.startswith(kept2) and SPLIT[len(kept2):len(kept2) + 1] == " "
                and "antidis" not in kept2,
                f"kept={kept2[-30:]!r} next={SPLIT[len(kept2):len(kept2) + 1]!r}")
        c.check("U4 ...and re-cutting it changes nothing (the sync is idempotent)",
                ag_description(cut) == cut, ag_description(cut))
        c.check("U5 ...and it stays ASCII (PS 5.1 writes these literals from a BOM-less .ps1)",
                cut.isascii(), cut)

        # ⭐ THE MEASUREMENT THAT IS THE TICKET: every workflow door within budget.
        # ⛔ HAND-OWNED DOORS ARE NOT EXEMPT. `smh-adviser-board.md` is authored rather than
        # generated, and the sync never rewrites it - but Antigravity reads its description into
        # the SAME menu, so exempting it would leave the biggest single row in place while the
        # check reported the budget met. Hand-owned means "fix it by hand", not "skip it".
        # The BRAINS' descriptions - uncut, i.e. the actual input the generator is given. The
        # workflow doors below carry the OUTPUT, so cutting those again would be idempotent and
        # prove nothing about the cut.
        AG_LIVE_DESCS = [d for d in
                         (fm_field(read(b), "description")
                          for b in sorted((ROOT / ".agents/commands").glob("*.md")))
                         if d]

        over, measured, total = [], 0, 0
        for wf_door in sorted((ROOT / ".agents/workflows").glob("*.md")):
            d = fm_field(read(wf_door), "description")
            if not d:
                continue
            measured += 1
            total += len(d)
            if len(d) > AG_DESC_MAX:
                over.append(f"{wf_door.name} ({len(d)})")
        c.check("U6 every .agents/workflows door fits Antigravity's menu budget",
                not over, f"{len(over)} over {AG_DESC_MAX}: {over[:8]}")
        # ⭐ THE CONTROL U-M4 PROVED WAS MISSING. "0 doors over budget" out of 0 doors read is
        # the vacuous green `tests-must-gate-for-real` names, and the mutant that stopped the
        # loop appending survived precisely there. The count and the TOTAL are both asserted:
        # the total is the number Antigravity's menu actually spends (13,883 -> 4,590 chars is
        # what SCC-195 bought), so a regression shows as a number rather than as silence.
        c.check("U6b ...and it read a real number of doors (not a silent empty sweep)",
                measured >= 30, f"only {measured} workflow descriptions read")
        # ⛔ U6d · THE TEETH CONTROL. U6 sweeps the LIVE tree, where a passing run is by
        # definition a run with nothing to report - so a detector that stopped recording
        # offenders entirely would read exactly like a clean tree, and did (U-M4 survived
        # both earlier rounds). The predicate is re-run here against a fabricated over-budget
        # door, where it MUST fire. A live sweep and a synthetic offender together are what
        # make "0 over budget" mean something.
        fake = "x" * (AG_DESC_MAX + 1)
        c.check("U6d CONTROL: the same predicate FIRES on a fabricated over-budget door",
                len(fake) > AG_DESC_MAX and ag_description(fake) != fake
                and len(ag_description(fake)) <= AG_DESC_MAX,
                f"a {len(fake)}-char description must not survive the budget")
        # ⛔ U6e · THE REWRITE MUST NOT CHANGE THE LINE ENDINGS. `Set-AgDescriptionLine` matched
        # `(.*)$`, and in .NET `.` matches CR while `$` sits before the LF - so on a CRLF brain
        # the CR was captured, TrimEnd() removed it, and the rewritten line shipped LF-only
        # among CRLF siblings: a mixed-ending file produced by a pure text edit. No brain is
        # CRLF today, which is exactly why this is pinned rather than noticed later (blind
        # lens, F14). The Python twin below is the one this suite can execute; both were fixed.
        crlf = "---\r\nname: x\r\ndescription: " + ("y" * (AG_DESC_MAX + 40)) + "\r\n---\r\n"
        outp = with_ag_description(crlf)
        c.check("U6e the description rewrite preserves CRLF line endings",
                outp.count("\r\n") == crlf.count("\r\n") and "\n" not in outp.replace("\r\n", ""),
                repr(outp[:120]))
        c.check("U6e CONTROL: ...and an LF brain gains no CR",
                "\r" not in with_ag_description(crlf.replace("\r\n", "\n")),
                repr(with_ag_description(crlf.replace("\r\n", "\n"))[:120]))

        # ⭐ U7 · THE TWINS, RUN AGAINST EACH OTHER FOR REAL. Everything above tests the
        # PYTHON emulation; the file that ships is `sync-agents.ps1`, and the claim "if the two
        # ever disagree the door reads stale" only holds if they agree. Until now that coupling
        # ran solely through committed artifacts - so an emulation drift showed up as an
        # unfixable `stale` on a GENERATED file, which is the SCC-194 wedge. This extracts the
        # real function and runs it under pwsh over every live description plus an astral
        # fixture, which is the one input the test-adequacy audit measured them disagreeing on.
        import shutil as _shutil
        pwsh = _shutil.which("pwsh")
        # ⛔ TWENTY, NOT ONE. A single astral character shifts the UTF-16 cut by one unit,
        # and the word-boundary trim absorbs that - so the mutant that reverts to code
        # points SURVIVED a fixture with one rocket in it. Twenty shifts the cut by twenty,
        # which lands in a different word, which is the only thing the two can disagree on.
        ASTRAL = "Ship " + "\U0001F680" * 20 + " the launch checklist " + ("word " * 40)
        if not pwsh:
            c.check("U7 SKIPPED: no pwsh on this machine - the twins are unverified here",
                    True, "install PowerShell 7 to run the real generator against the emulation")
        else:
            src = (ROOT / ".agents/scripts/sync-agents.ps1").read_text(encoding="utf-8")
            i = src.index("function Get-AgDescription")
            fn = src[i:src.index("\n}", i) + 2]
            probes = [d for d in AG_LIVE_DESCS] + [ASTRAL]
            script = (fn + "\n$in = [Console]::In.ReadToEnd() -split \"\\u0000\"\n"
                      + "$out = foreach ($d in $in) { Get-AgDescription $d }\n"
                      + "[Console]::Out.Write(($out -join \"`u{0}\"))\n")
            r = subprocess.run([pwsh, "-NoProfile", "-Command", "-"], input=script + "\n",
                               capture_output=True, text=True, encoding="utf-8")
            # the script is fed on stdin as the command; the probe payload goes via a temp file
            with TempDir() as _t:
                sp = _t / "probe.ps1"
                dp = _t / "in.txt"
                dp.write_text("\u0000".join(probes), encoding="utf-8")
                sp.write_text(fn + "\n$in = [IO.File]::ReadAllText('" + str(dp).replace("\\", "\\\\")
                              + "', [Text.Encoding]::UTF8) -split \"`u{0}\"\n"
                              + "$out = foreach ($d in $in) { Get-AgDescription $d }\n"
                              + "[IO.File]::WriteAllText('" + str(_t / "out.txt").replace("\\", "\\\\")
                              + "', ($out -join \"`u{0}\"), (New-Object Text.UTF8Encoding $false))\n",
                              encoding="utf-8")
                r = subprocess.run([pwsh, "-NoProfile", "-File", str(sp)],
                                   capture_output=True, text=True)
                got = ((_t / "out.txt").read_text(encoding="utf-8").split("\u0000")
                       if (_t / "out.txt").is_file() else [])
            want = [ag_description(d) for d in probes]
            c.check("U7 the REAL PowerShell generator and this file's emulation agree, "
                    "on every live description AND on an astral character",
                    got == want,
                    f"pwsh rc={r.returncode} {r.stderr.strip()[:200]} | "
                    + next((f"{i}: {g!r} != {w!r}"
                            for i, (g, w) in enumerate(zip(got, want)) if g != w),
                           f"lengths {len(got)} vs {len(want)}"))
            c.check("U7 CONTROL: the astral fixture is genuinely over budget and non-BMP",
                    len(ASTRAL) > AG_DESC_MAX and max(ord(ch) for ch in ASTRAL) > 0xFFFF,
                    f"{len(ASTRAL)} chars, max ord {max(ord(ch) for ch in ASTRAL):#x}")

        # U8 · the budgeted-mirror ARM of door_verdict, as pure strings. Every other shape it
        # can return has a synthetic control; this one had only the live sweep, where a broken
        # comparison and a clean tree read the same.
        _brain = "---\nname: x\ndescription: " + ("z" * 300) + "\nplatforms: [antigravity]\n---\nbody\n"
        c.check("U8 CONTROL: a mirror carrying the CUT description is parity, not stale",
                with_ag_description(_brain) != _brain
                and with_ag_description(with_ag_description(_brain)) == with_ag_description(_brain),
                "the budgeted form must be the fixed point the mirror is compared against")
        c.check("U8 CONTROL: ...and one changed body word is NOT",
                with_ag_description(_brain).replace("body", "bodyy") != with_ag_description(_brain),
                "the comparison must still see everything below the description line")

        # U9 · green-first characterization, scoped to THE MENU. Most rows are now truncated,
        # and what the menu is FOR is telling the commands apart - two rows that read the same
        # for their first 60 characters are two commands the model cannot choose between.
        # ⛔ SCOPED TO `.agents/workflows`, NOT to every brain: `qa.md` and `tea.md` share a
        # 60-char prefix and are `platforms: [opencode]`, so they never reach this menu. A pin
        # that reds on doors the surface does not carry would be measuring the wrong surface.
        _menu = [d for d in (fm_field(read(w), "description")
                             for w in sorted((ROOT / ".agents/workflows").glob("*.md"))) if d]
        c.check("U9 the menu's descriptions stay pairwise distinct in their first 60 chars",
                len({d[:60] for d in _menu}) == len(_menu) and len(_menu) >= 30,
                f"{len(_menu)} menu rows, {len({d[:60] for d in _menu})} distinct 60-char prefixes")

        c.check("U6c ...and the whole menu payload stays under the budget it was cut to",
                total <= measured * AG_DESC_MAX and total < 6000,
                f"{measured} descriptions, {total} chars total (was 13,883 before SCC-195)")

        # And the control: the BRAINS are deliberately NOT shortened. The command is written for
        # an agent that has already chosen it; only the menu has a budget. If this ever goes
        # green-because-empty, the shortening leaked into the source of truth.
        long_brains = [p.name for p in sorted((ROOT / ".agents/commands").glob("*.md"))
                       if (fm_field(read(p), "description") or "") and
                       len(fm_field(read(p), "description")) > AG_DESC_MAX]
        c.check("U7 CONTROL: the BRAINS keep their full descriptions (the budget is the menu's)",
                len(long_brains) >= 10, f"only {len(long_brains)} long brains - did the "
                                        f"shortening leak into .agents/commands?")

    return c.finish()


if __name__ == "__main__":
    raise SystemExit(main())
