"""One door per platform per command (SCC-66) — the contract that keeps four menus honest.

Command docs, skill launchers, sync instructions and the actual on-disk caches used to be four
independent claims about the same thing, and they disagreed: 19 commands published BOTH a
`.claude/commands` mirror and a skill, Codex carried a deprecated `/prompts:` twin beside its
native skill, and the only way to notice was for a human to open a menu and find it wrong. That
is what burned the failed session this program came from.

The door model, and why it is forced rather than chosen:
  * Codex cannot expose repo-defined top-level `/name` commands at all — skills are its ONLY door;
  * Claude Code publishes a slash command for every `.claude/skills/*/SKILL.md` — so a skill is
    already a Claude door, and a command mirror beside it is a second one;
  * therefore ONE launcher skill serves Claude and Codex both, and `.claude/commands` +
    `~/.codex/prompts` are retired. opencode keeps its command mirror; Antigravity its workflow
    mirror (thin launcher when the body clears its 12k cap).

Reach comes from `platforms:` frontmatter (absent = universal), which splits the skill door two
ways: `.agents/skills` is Codex's NATIVE surface, so a claude-only command's launcher must live in
the `.claude/skills` cache only, and a codex-only command's launcher must be kept OUT of that cache.
Both directions are asserted — a door in the wrong place is exactly as wrong as a missing one.
"""
from __future__ import annotations

import re
from pathlib import Path

from _harness import Cases

ROOT = Path(__file__).resolve().parents[3]
ALL = ("claude", "opencode", "antigravity", "codex")
GEN = "GENERATED by sync-agents"

def wf_hand_owned(sync_ps1: str) -> set[str]:
    """workflows/ files the sync engine deliberately never writes — read FROM the engine.

    ⭐ Derived, not restated. This was `{"INDEX.md"}`: a hand-copied subset of the engine's
    three-entry `$excluded`, missing `smh-update-maps-indexes.md` and `smh-adviser-board.md`,
    which are hand-authored Antigravity workflows that legitimately differ from their command
    bodies (one is a condensed 2 KB variant of a 52 KB brain; the other is a 40 KB doc whose
    brain was later rewritten to 4 KB). The door-parity check below reported both as drift on
    its first run — a false positive caused entirely by the duplicated list.

    Two parsers of one fact must agree, so this reads the fact instead of copying it. A parse
    that returns nothing fails SAFE (nothing is exempted, so the sweep gets noisier, never
    quieter); the assertion in main() pins that it parsed at all.
    """
    m = re.search(r"\$excluded\s*=\s*@\(([^)]*)\)", sync_ps1)
    return set(re.findall(r"'([^']+)'", m.group(1))) if m else set()


def read(p: Path) -> str:
    # utf-8-SIG, not utf-8: 8 testarch-* commands carry a UTF-8 BOM. PowerShell's ReadAllLines
    # strips it, so sync-agents reads their `platforms: [opencode]` correctly - a plain utf-8 read
    # here leaves `﻿---` on line 1, which str.strip() does NOT remove (U+FEFF is not Python
    # whitespace), so the frontmatter probe misses and every one of them reads as UNIVERSAL. The
    # test then demands Claude/Codex/Antigravity doors for eight opencode-only bridges. Two parsers
    # of one file must agree byte-for-byte or the gate invents work.
    return p.read_text(encoding="utf-8-sig", errors="replace")


def platforms(cmd: Path) -> tuple[str, ...]:
    """Same parse as sync-agents' Get-CommandPlatforms: absent = universal, [] = nowhere."""
    lines = read(cmd).splitlines()
    if not lines or lines[0].strip() != "---":
        return ALL
    for ln in lines[1:60]:
        if ln.strip() == "---":
            break
        m = re.match(r"\s*platforms:\s*\[(.*?)\]", ln)
        if m:
            return tuple(x.strip().strip("\"'").lower() for x in m.group(1).split(",") if x.strip())
    return ALL


def main() -> int:
    c = Cases("command surface contracts")

    cmds = sorted(p for p in (ROOT / ".agents/commands").glob("*.md")
                  if not p.stem.endswith("-AP") and p.name != "INDEX.md")
    master_skills = ROOT / ".agents/skills"
    claude_skills = ROOT / ".claude/skills"

    # ── The retired doors stay retired ────────────────────────────────────────
    stale_cmd_mirror = sorted(p.name for p in (ROOT / ".claude/commands").glob("*.md"))
    c.check("`.claude/commands` is a retired door - no command mirrors there",
            not stale_cmd_mirror,
            f"{len(stale_cmd_mirror)} left: {stale_cmd_mirror[:6]}")

    sync_ps1 = read(ROOT / ".agents/scripts/sync-agents.ps1")

    # The engine's own hand-owned list, read rather than restated (see wf_hand_owned).
    # Pinned non-empty: a regex that stopped matching would exempt NOTHING here, but the same
    # value gates the ghost check below, where an empty set is the SAFE direction and a
    # runaway one is not. Assert it parsed, so a silent parse failure cannot drift either way.
    hand_owned = wf_hand_owned(sync_ps1)
    c.check("the hand-owned workflow list was READ from the sync engine, not guessed",
            2 <= len(hand_owned) <= 8 and "INDEX.md" in hand_owned,
            f"parsed {sorted(hand_owned)} from sync-agents.ps1 $excluded")

    c.check("the sync engine states the door model and both retirements",
            "THE DOOR MODEL" in sync_ps1
            and "codex prompts cache RETIRED" in sync_ps1
            and "Claude's door is .claude\\skills" in sync_ps1,
            "sync-agents.ps1 no longer states the door model + both retirements")

    # ── Every eligible command has EXACTLY ONE door on each platform it claims ─
    missing_skill, wrong_place, bad_body = [], [], []
    missing_oc, missing_ag = [], []
    for cmd in cmds:
        pl = platforms(cmd)
        name = cmd.stem
        in_master = (master_skills / name / "SKILL.md").is_file()
        in_cache = (claude_skills / name / "SKILL.md").is_file()

        if "codex" in pl:
            # Codex reads .agents/skills directly - the door must be in the master.
            if not in_master:
                missing_skill.append(f"{name} (codex)")
            if "claude" not in pl and in_cache:
                wrong_place.append(f"{name}: codex-only but present in .claude/skills")
        if "claude" in pl:
            # Claude's menu reads the cache; a claude-only launcher must NOT sit in the
            # Codex-visible master.
            if not in_cache:
                missing_skill.append(f"{name} (claude)")
            if "codex" not in pl and in_master:
                wrong_place.append(f"{name}: claude-only but present in .agents/skills")

        # Whichever copy exists, a GENERATED launcher must point at its own command body.
        for sk in (master_skills / name / "SKILL.md", claude_skills / name / "SKILL.md"):
            if sk.is_file():
                body = read(sk)
                if GEN in body and not (f".agents/commands/{cmd.name}" in body
                                        and "END TO END" in body):
                    bad_body.append(str(sk.relative_to(ROOT)))

        if "opencode" in pl and not (ROOT / ".opencode/commands" / cmd.name).is_file():
            missing_oc.append(name)
        if "antigravity" in pl and not (ROOT / ".agents/workflows" / cmd.name).is_file():
            missing_ag.append(name)

    c.check("every claude/codex-eligible command has its skill door",
            not missing_skill, f"{len(missing_skill)} missing: {missing_skill[:6]}")
    c.check("no door sits on a platform its command does not claim",
            not wrong_place, f"{len(wrong_place)}: {wrong_place[:4]}")
    c.check("every generated launcher points at its own command body, END TO END",
            not bad_body, f"{len(bad_body)}: {bad_body[:4]}")
    c.check("every opencode-eligible command has its mirror",
            not missing_oc, f"{len(missing_oc)} missing: {missing_oc[:6]}")
    c.check("every antigravity-eligible command has its workflow mirror (thin launcher counts)",
            not missing_ag, f"{len(missing_ag)} missing: {missing_ag[:6]}")

    # ── Door CONTENT parity (SCC-113 follow-on) ──────────────────────────────
    # Every check above asks whether a door EXISTS. None asks whether it still says what its
    # brain says, and that gap shipped a live break: SCC-77 landed the armed `main` write gate
    # on `main` without running /smh-sync-agents, so `.opencode/commands/` and
    # `.agents/workflows/` kept the pre-token merge steps while MAIN-PUSH-ENFORCE was armed.
    # An opencode or Antigravity agent following them reaches `git push origin main` with no
    # token and is refused, with nothing in its instructions telling it to mint one. Claude and
    # Codex were fine - their doors are thin launchers that read the brain live, which is
    # exactly why the drift was invisible to a human spot-check.
    #
    # SCC-77's close-out reported a fully green floor. This is the check that was missing.

    def door_verdict(brain: str, body: str, cmd_name: str) -> str:
        """'ok' | 'stale' | 'unmarked' - for ONE mirror door against its command body.

        A mirror is one of exactly two legal things:
          * a FULL MIRROR, byte-identical to the brain; or
          * a THIN LAUNCHER, emitted when the body clears Antigravity's 12k cap.

        ⭐ The launcher exemption must be EARNED, not announced. Accepting any file carrying
        the GENERATED marker makes a drifted launcher invisible - and a launcher is ~15 lines
        whose entire job is naming its command, so one pointing at a renamed or deleted brain
        is the realistic failure. The marker plus the pairing the existing launcher check
        already demands (names THIS command body, says END TO END) is the exemption.
        """
        if body == brain:
            return "ok"
        if GEN in body and f".agents/commands/{cmd_name}" in body and "END TO END" in body:
            return "ok"
        if GEN in body:
            return "unmarked"      # claims to be generated but does not name its own brain
        return "stale"

    # Controls first, as pure string cases - the live sweep below can only ever prove the
    # tree is currently clean, which is not the same as proving the check has teeth.
    BRAIN = "---\nplatforms: [opencode]\n---\n# /x\n\nfull body, many lines\n"
    LAUNCHER = ("# /x - launcher (GENERATED by sync-agents; do not edit)\n"
                "read `.agents/commands/x.md` and follow it END TO END\n")
    c.check("door-parity CONTROL: an identical mirror is ok",
            door_verdict(BRAIN, BRAIN, "x.md") == "ok")
    c.check("door-parity CONTROL: a STALE mirror is caught",
            door_verdict(BRAIN, BRAIN.replace("full body, many lines", "old body"), "x.md")
            == "stale",
            "this is the SCC-77 shape - a door that still reads the pre-change steps")
    c.check("door-parity CONTROL: a truncated mirror is caught",
            door_verdict(BRAIN, "---\nplatforms: [opencode]\n---\n# /x\n", "x.md") == "stale")
    c.check("door-parity CONTROL: a real thin launcher is exempt",
            door_verdict(BRAIN, LAUNCHER, "x.md") == "ok")
    c.check("door-parity CONTROL: a launcher naming the WRONG brain is caught",
            door_verdict(BRAIN, LAUNCHER.replace("x.md", "y.md"), "x.md") == "unmarked",
            "the exemption is earned by the pairing, not announced by the marker")
    c.check("door-parity CONTROL: the marker alone does NOT excuse drift",
            door_verdict(BRAIN, "# GENERATED by sync-agents\nanything at all\n", "x.md")
            == "unmarked")

    MIRRORS = (".opencode/commands", ".agents/workflows")
    drifted, examined = [], 0
    for cmd in cmds:
        brain = read(cmd)
        for rel in MIRRORS:
            # A hand-owned workflow is authored, not generated, and legitimately differs from
            # its brain — `smh-adviser-board` is a condensed 2 KB Antigravity variant of a
            # 52 KB command. The engine never writes these, so parity is not the contract.
            if rel == ".agents/workflows" and cmd.name in hand_owned:
                continue
            door = ROOT / rel / cmd.name
            if not door.is_file():
                continue
            examined += 1
            v = door_verdict(brain, read(door), cmd.name)
            if v != "ok":
                drifted.append(f"{rel}/{cmd.name} [{v}]")

    c.check("every mirror door still says what its brain says",
            not drifted,
            f"{len(drifted)} drifted - run /smh-sync-agents: {drifted[:6]}")

    # ⭐ An empty sweep is indistinguishable from a clean one, and "0 offenders" out of 0 doors
    # is the vacuous green `tests-must-gate-for-real` names. A renamed cache directory or a
    # typo'd glob would otherwise read as a pass forever.
    c.check("door-parity examined a real number of doors (not a silent empty sweep)",
            examined >= 40, f"only {examined} mirror doors examined")

    # ── Positive control: the generator must actually be generating ───────────
    # Without this, every check above passes trivially if the emit stage silently no-ops.
    generated = [d.name for d in master_skills.iterdir()
                 if (d / "SKILL.md").is_file() and GEN in read(d / "SKILL.md")]
    c.check("the launcher generator produced doors (not a silent no-op)",
            len(generated) >= 10, f"only {len(generated)} generated launchers")

    # ── Hand-authored skills are never overwritten by the generator ───────────
    # These carry real content (boundaries, routing notes) a stub would destroy.
    hand = ["cicd-park", "cicd-resume", "cicd-close-workingtree", "smh-close-task-merge-tree",
            "cicd-update-sprint-memory", "smh-update-maps-indexes"]
    clobbered = [n for n in hand
                 if (master_skills / n / "SKILL.md").is_file()
                 and GEN in read(master_skills / n / "SKILL.md")]
    c.check("hand-authored skills survive a sync untouched",
            not clobbered, f"overwritten by the generator: {clobbered}")

    # ── Every skill door is loadable: frontmatter with a description ──────────
    no_fm = []
    for d in sorted(master_skills.iterdir()):
        sk = d / "SKILL.md"
        if not sk.is_file():
            continue
        head = read(sk)[:1200]
        if not head.startswith("---") or "description:" not in head:
            no_fm.append(d.name)
    c.check("every skill door carries frontmatter with a description",
            not no_fm, f"{len(no_fm)}: {no_fm[:6]}")

    # ── Stale mirrors: a workflow with no command source is a ghost ───────────
    cmd_names = {p.name for p in (ROOT / ".agents/commands").glob("*.md")}
    ghosts = sorted(p.name for p in (ROOT / ".agents/workflows").glob("*.md")
                    if p.name not in cmd_names and p.name not in hand_owned)
    c.check("no ghost workflow mirrors (every one has a command source)",
            not ghosts, f"{len(ghosts)}: {ghosts[:6]}")

    # ── The docs agree with the engine ────────────────────────────────────────
    agents_md = read(ROOT / "AGENTS.md")
    c.check("root AGENTS.md documents the door model for every platform",
            "one door per platform per command" in agents_md.lower()
            and "launcher skill" in agents_md,
            "AGENTS.md no longer documents the door model")
    sync_cmd = read(ROOT / ".agents/commands/smh-sync-agents.md")
    c.check("sync-agents command doc names both retired doors",
            "RETIRED door" in sync_cmd and "/prompts:<name>" in sync_cmd
            and "Do not use `-Maintained`" in sync_cmd,
            "smh-sync-agents.md no longer matches what the engine does")

    return c.finish()


if __name__ == "__main__":
    raise SystemExit(main())
