#!/bin/sh
# commit-msg-jira — require a Jira work-item key in every commit message.
#
# Installed as <hooks-dir>/commit-msg. The hooks dir is `core.hooksPath` when set, else
# .git/hooks — see pre-commit-encoding.sh for why that distinction has already cost us once.
#
# Why this exists: the Jira audit trail is only as good as the weakest commit. Atlassian's
# GitHub app links a commit to a work item by finding the key as a literal string in the
# message (or the branch name) — there is no other join. One unkeyed commit is one change to
# production that no ticket can account for, and it is invisible until someone goes looking
# months later.
#
# ─── SCOPE IS DELIBERATELY NARROW ──────────────────────────────────────────────────────────
# This checks the key's SHAPE, not its existence. A live "does AVCH-57 exist?" call would put
# a network round-trip on every commit and would fail closed on a plane. Typo'd-but-well-formed
# keys are caught downstream, where a check can be slow: the Jira board simply never shows the
# commit. Do not grow this hook — the encoding hook's header says it best, a slow hook is a
# disabled hook.
#
# ─── MODES ─────────────────────────────────────────────────────────────────────────────────
#   default          WARN  — prints the complaint, lets the commit through.
#   JIRA-ENFORCE     BLOCK — rejects the commit. Create the file to arm it:
#                            touch .agents/scripts/git-hooks/JIRA-ENFORCE
# Roll out in WARN for a few days first. A hook that starts by blocking a commit you were
# midway through gets --no-verify'd forever after.
#
# Kill switch: create .agents/scripts/git-hooks/DISABLE (untracked) to turn it off entirely.
# Bypass once: git commit --no-verify

MSG_FILE="$1"
[ -n "$MSG_FILE" ] || exit 0

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$REPO_ROOT" || exit 0

[ -f scripts/git-hooks/DISABLE ] && exit 0
[ -f .agents/scripts/git-hooks/DISABLE ] && exit 0

# ─── Which keys does THIS repo answer to? ──────────────────────────────────────────────────
# Declared in a tracked file so it travels with the clone. A repo with no jira.conf has no
# gate at all — same graceful degradation as the encoding hook in a repo with no toolkit.
JIRA_KEYS=""
[ -f .agents/jira.conf ] && . ./.agents/jira.conf
[ -n "$JIRA_KEYS" ] || exit 0

# ─── Carve-outs ────────────────────────────────────────────────────────────────────────────
# Merge and revert messages are generated by git and cannot sanely carry a key; a rebase
# replays commits that were already checked once. Blocking any of these means blocking the
# tool, not the author. (Ruling 2026-08-07: every chore/* branch DOES need its own ticket —
# these three are the only exemptions.)
#
# ⛔ `$(git rev-parse --git-dir)`, NOT the literal `.git/` (SCC-144). In a WORKTREE `.git` is a
# FILE, not a directory — the real state lives in `.git/worktrees/<name>/` — so a literal path
# probe is ALWAYS FALSE there, and every lane in this system is a worktree. This carve-out was
# therefore live in the shared checkout and dead in every lane: the absorb-main merge that
# /smh-merge-multiple-workingtrees Step 4b performs INSIDE the lane was gated while the identical
# merge in the shared checkout was exempt. The subject fallback below does not cover it either —
# it matches a capital `Merge `, while this repo's own merges read `merge: chore/... -> main`.
GITDIR=$(git rev-parse --git-dir 2>/dev/null) || GITDIR=.git
if [ -f "$GITDIR/MERGE_HEAD" ] || [ -d "$GITDIR/rebase-merge" ] || [ -d "$GITDIR/rebase-apply" ]; then
  exit 0
fi

# Strip the comment block before matching. git appends "On branch claude/AVCH-57-foo" and the
# staged-file list to the message file; on a correctly-named branch that text contains the key,
# so an unstripped grep passes every commit and the gate silently does nothing.
SUBJECT=$(grep -v '^#' "$MSG_FILE" | sed -e 's/[[:space:]]*$//' -e '/^$/d')

case "$SUBJECT" in
  'Revert "'*|'Merge '*|'fixup! '*|'squash! '*) exit 0 ;;
esac

# ─── The check ─────────────────────────────────────────────────────────────────────────────
PATTERN="($(echo "$JIRA_KEYS" | tr ' ' '|'))-[0-9]+"

if printf '%s\n' "$SUBJECT" | grep -Eq "$PATTERN"; then
  exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
SUGGEST=$(printf '%s\n' "$BRANCH" | grep -Eo "$PATTERN" | head -1)

echo ""
echo "  ✖ No Jira work-item key in this commit message."
echo ""
echo "    Expected one of: $(echo "$JIRA_KEYS" | tr ' ' ',') followed by -<number>"
echo "    Example:         AVCH-57 fix(db): stop re-initialising the Firestore client"
if [ -n "$SUGGEST" ]; then
  echo ""
  echo "    Your branch says $SUGGEST — that is almost certainly the key you want."
fi
echo ""

if [ -f .agents/scripts/git-hooks/JIRA-ENFORCE ]; then
  echo "    Commit rejected. Add the key, or --no-verify if this genuinely has no ticket."
  echo ""
  exit 1
fi

echo "    (warn-only — commit allowed. Arm the gate with:"
echo "     touch .agents/scripts/git-hooks/JIRA-ENFORCE)"
echo ""
exit 0
