#!/usr/bin/env python3
"""review_scope.py - what a lens actually reads: one PART, and the masters only. (SCC-447)

THE MEASUREMENT. SCC-441 handed the review engine `origin/main..HEAD`: 155 files, 1.46 MB.
Forty-eight of those files were byte-copy MIRRORS of files already in the same diff, and
twenty-six were the lane's OWN records - the walkthrough describing the work, the plan, the
operations manual page. A lens that reads a mirror finds the same defect twice and reports it
twice; a lens that reads the walkthrough reviews the DESCRIPTION of the code instead of the
code. The same diff through this script is 82 files and 618 KB - measured 2026-09-11 by running
this script over the SCC-441 merge (`03778605^1..03778605`), not estimated.

    review_scope.py --repo <worktree> --base origin/main \\
                    [--key <PART-KEY> | --range <sha>..<sha>] [--audit] \\
                    [--out <artifacts>/review/diff.patch]

TWO HALVES, deliberately separate.

WHICH COMMITS. A lane is not a review. Commits in `base..HEAD` are grouped by PART: every
`[A-Z]+-\\d+` in a subject is read, and a key that is not the lane's own key is the part -
the house rider convention, `SCC-<parent> rider SCC-<child>: ...` (`work-consolidation.md`
rule 2). A subject carrying only the lane key belongs to the lane. Reading left-to-right
instead would file every rider under the parent, which is the bug the convention exists to
prevent. More than one part in range and no selector is EXIT 2 naming the keys - never a
guess, because guessing produces a review of the wrong thing that looks exactly like a review
of the right thing. A lane whose parts carry no rider keys selects by `--range`.

WHICH FILES. Three withheld classes, each a different way of reading the same thing twice:

    mirror      `.opencode/` `.roo/` `.claude/` `.agent/`  - byte copies of a master
    generated   text carries `GENERATED by sync-agents`    - output, not authorship
    record      `_artifacts/` `_bmad-output/` `docs/_scc_sops_prds/` - the lane describing itself

Every withheld path is PRINTED with its class. A filter nobody can see is a filter nobody can
correct, and the one thing worse than a lens reading too much is a lens silently reading too
little.

⛔ THERE IS NO BYTE CAP, and that is a refusal rather than an omission. A cap truncates at an
arbitrary line and the lens never learns what it did not see - a gap invisible from inside the
review, which is the one kind of gap a review cannot catch. The size of a review is the size of
a part; a part too big to review is a part that should have been two.

⭐ `--audit` IS THE ASYMMETRY (D9). A self-audit keeps every MIRROR, because drift between a
master and its copy is the defect it exists to hunt - and still strips every RECORD, because a
self-audit reading the plan it is auditing against grades the plan by itself.

Both machines: stdlib only, `python3`/`python` never assumed by callers.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

KEY_RE = re.compile(r"[A-Z]+-\d+")
GENERATED_MARKER = "GENERATED by sync-agents"

MIRROR_PREFIXES = (".opencode/", ".roo/", ".claude/", ".agent/")
RECORD_PREFIXES = ("_artifacts/", "_bmad-output/", "docs/_scc_sops_prds/")


def git(repo: Path, *args: str) -> str:
    """Run git in `repo` and return stdout, or die naming the command that failed."""
    out = subprocess.run(("git", *args), cwd=repo, capture_output=True, text=True,
                         encoding="utf-8", errors="replace")
    if out.returncode != 0:
        die(f"git {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout


def git_ok(repo: Path, *args: str) -> tuple[int, str]:
    """Run git in `repo` and return (exit code, stdout) without dying."""
    out = subprocess.run(("git", *args), cwd=repo, capture_output=True, text=True,
                         encoding="utf-8", errors="replace")
    return out.returncode, out.stdout


def die(msg: str, code: int = 2) -> None:
    print(f"review_scope: {msg}", file=sys.stderr)
    sys.exit(code)


def lane_key(repo: Path) -> str:
    """The lane's own key, read from the branch name the way every other gate here reads it.

    `task_preflight.py --expect-key` and `post-commit-jira-start.sh` both parse the key out of
    the branch, so a lane that renames its branch renames its key everywhere at once.
    """
    branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD").strip()
    found = KEY_RE.findall(branch.upper())
    return found[0] if found else ""


def part_key_of(subject: str, lane: str) -> str:
    """The PART a commit belongs to: a key that is not the lane's, else the lane's own."""
    keys = KEY_RE.findall(subject)
    for k in keys:
        if k != lane:
            return k
    return lane or (keys[0] if keys else "(no key)")


def group_commits(repo: Path, base: str, lane: str) -> dict[str, list[str]]:
    """Map part key -> the commit shas in `base..HEAD` that belong to it, oldest first."""
    raw = git(repo, "log", "--reverse", "--format=%H%x1f%s", f"{base}..HEAD")
    groups: dict[str, list[str]] = {}
    for line in raw.splitlines():
        if "\x1f" not in line:
            continue
        sha, subject = line.split("\x1f", 1)
        groups.setdefault(part_key_of(subject, lane), []).append(sha)
    return groups


def files_of(repo: Path, shas: list[str]) -> list[str]:
    """Every path the given commits touched, de-duplicated, in stable order."""
    seen: dict[str, None] = {}
    for sha in shas:
        for path in git(repo, "show", "--pretty=format:", "--name-only", sha).splitlines():
            if path.strip():
                seen.setdefault(path.strip(), None)
    return list(seen)


def classify(repo: Path, path: str, ref: str, audit: bool) -> str | None:
    """The withheld class for `path`, or None when a lens should read it.

    Record is tested FIRST so a record that also lives under a mirror prefix is reported as
    what it is. Under `--audit` the mirror class is not withheld at all (D9).
    """
    if path.startswith(RECORD_PREFIXES):
        return "record"
    code, text = git_ok(repo, "show", f"{ref}:{path}")
    if code == 0 and GENERATED_MARKER in text:
        return "generated"
    if path.startswith(MIRROR_PREFIXES):
        return None if audit else "mirror"
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description="the diff a review lens reads: one part, masters only")
    ap.add_argument("--repo", required=True, help="the worktree the diff comes from")
    ap.add_argument("--base", default="origin/main", help="the ref the lane was cut from")
    sel = ap.add_mutually_exclusive_group()
    sel.add_argument("--key", help="select one PART by its ticket key")
    sel.add_argument("--range", dest="rng", metavar="A..B", help="select explicit commits")
    ap.add_argument("--audit", action="store_true",
                    help="self-audit scope: keep every mirror, still strip every record")
    ap.add_argument("--out", help="write the patch here (omit for a dry-run report)")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    if not (repo / ".git").exists():
        die(f"{repo} is not a git worktree")

    lane = lane_key(repo)

    # ── which commits ──────────────────────────────────────────────────────────────────
    if args.rng:
        if ".." not in args.rng:
            die(f"--range wants A..B, got {args.rng!r}")
        lo, hi = args.rng.split("..", 1)
        shas = [s for s in git(repo, "log", "--reverse", "--format=%H", args.rng).splitlines() if s]
        diff_from, diff_to = lo, hi
        chosen = args.rng
    else:
        groups = group_commits(repo, args.base, lane)
        if not groups:
            die(f"selection is empty: no commits in {args.base}..HEAD")
        for key in sorted(groups):
            print(f"  part {key}  {len(groups[key])} commit(s)")
        if args.key:
            if args.key not in groups:
                die(f"selection is empty: no commits for {args.key} in {args.base}..HEAD")
            shas = groups[args.key]
            chosen = args.key
        elif len(groups) > 1:
            die("this range holds more than one part - name one with --key or --range: "
                + ", ".join(sorted(groups)))
        else:
            chosen = next(iter(groups))
            shas = groups[chosen]
        diff_from, diff_to = args.base, "HEAD"

    if not shas:
        die(f"selection is empty: {chosen} selected no commits")

    # ── which files ────────────────────────────────────────────────────────────────────
    kept: list[str] = []
    withheld: list[tuple[str, str]] = []
    for path in files_of(repo, shas):
        cls = classify(repo, path, diff_to, args.audit)
        if cls:
            withheld.append((path, cls))
        else:
            kept.append(path)

    for path, cls in withheld:
        print(f"  withheld  {cls:<10} {path}")
    for path in kept:
        print(f"  kept      {'':<10} {path}")

    if not kept:
        die(f"selection is empty: every file in {chosen} was withheld "
            f"({len(withheld)} withheld) - there is nothing for a lens to read")

    patch = git(repo, "diff", f"{diff_from}..{diff_to}", "--", *kept)
    size = len(patch.encode("utf-8"))
    print(f"\nscope {chosen}{' (audit)' if args.audit else ''}: "
          f"kept: {len(kept)} file(s), {size} bytes · withheld: {len(withheld)} file(s)")

    if args.out:
        dest = Path(args.out)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(patch, encoding="utf-8")
        print(f"patch: {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
